
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// 
// This template generates PublicResXFileCodeGenerator compatible code plus some
// useful extensions. 
// 
// The original version provided by ResXResourceManager is restricted to resource key names
// that are valid c# identifiers to keep this template simple (KISS!).
// 
// Us it as it is or as a scaffold to generate the code you need.
//
// As long as you have ResXResourceManager running in the background, the generated code 
// will be kept up to date.
//  
//------------------------------------------------------------------------------

namespace CastelloBranco.DataAnnotations.Resources {
    using System;
    using System.Threading;
    using System.ComponentModel;

    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by a text template.
    // To add or remove a member, edit your .ResX file.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("ResXResourceManager", "1.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResources : INotifyPropertyChanged  {
        
        private static SharedResources Instance = new SharedResources ();

        private static global::System.Resources.ResourceManager resourceMan;
        
        // private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CastelloBranco.DataAnnotations.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                // return resourceCulture;

                return Thread.CurrentThread.CurrentUICulture;
            }
            set {
                // resourceCulture = value;

                Thread.CurrentThread.CurrentCulture   = 
                Thread.CurrentThread.CurrentUICulture = value; 

                Instance.PropertyChanged?.Invoke(Instance, new PropertyChangedEventArgs(""));    
            }
        }

        public string? this[string key]
        {
            get
            {
                return ResourceManager.GetString(key, Thread.CurrentThread.CurrentUICulture);
            }
        }

        public event PropertyChangedEventHandler? PropertyChanged;


        /// <summary>
        ///   Looks up a localized string similar to "As senhas não sâo iguais"
        /// </summary>
        public static string AsSenhasNãoSâoIguais {
            get {
                return ResourceManager.GetString("AsSenhasNãoSâoIguais", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CEP Inválido"
        /// </summary>
        public static string CEPInválido {
            get {
                return ResourceManager.GetString("CEPInválido", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CNPJ Inválido"
        /// </summary>
        public static string CNPJInválido {
            get {
                return ResourceManager.GetString("CNPJInválido", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "CPF Inválido"
        /// </summary>
        public static string CPFInválido {
            get {
                return ResourceManager.GetString("CPFInválido", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Data Inválida"
        /// </summary>
        public static string DataInválidaErrorMessage {
            get {
                return ResourceManager.GetString("DataInválidaErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "'{0}' precisa ser maior que '{1}'"
        /// </summary>
        public static string DateTimeOffsetDateGreaterThanErrorMessage {
            get {
                return ResourceManager.GetString("DateTimeOffsetDateGreaterThanErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "DDD Inválido"
        /// </summary>
        public static string DDDInvalido {
            get {
                return ResourceManager.GetString("DDDInvalido", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha nao pode ter sequencia crescente (por ex.123..."
        /// </summary>
        public static string DontAllowAscendentSequenceErrorMessage {
            get {
                return ResourceManager.GetString("DontAllowAscendentSequenceErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha nao pode ter sequencia crescente (por ex. 32..."
        /// </summary>
        public static string DontAllowDescendentSequenceErrorMessage {
            get {
                return ResourceManager.GetString("DontAllowDescendentSequenceErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha nao pode conter caracteres repetidos"
        /// </summary>
        public static string DontAllowRepeatsErrorMessage {
            get {
                return ResourceManager.GetString("DontAllowRepeatsErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "{0} é obrigatório(a)"
        /// </summary>
        public static string éobrigatórioa {
            get {
                return ResourceManager.GetString("éobrigatórioa", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Estado Inválido"
        /// </summary>
        public static string EstadoInvalido {
            get {
                return ResourceManager.GetString("EstadoInvalido", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Idade não permitida"
        /// </summary>
        public static string Idadenãopermitida {
            get {
                return ResourceManager.GetString("Idadenãopermitida", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Identificação"
        /// </summary>
        public static string Identificação {
            get {
                return ResourceManager.GetString("Identificação", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Identificação é obrigatória"
        /// </summary>
        public static string Identificaçãoéobrigatória {
            get {
                return ResourceManager.GetString("Identificaçãoéobrigatória", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Idioma"
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Idiomas"
        /// </summary>
        public static string Idiomas {
            get {
                return ResourceManager.GetString("Idiomas", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Inglês"
        /// </summary>
        public static string Inglês {
            get {
                return ResourceManager.GetString("Inglês", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Esta opção precisa estar marcada"
        /// </summary>
        public static string IsCheckedErrorMessage {
            get {
                return ResourceManager.GetString("IsCheckedErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Nome Completo Inválido"
        /// </summary>
        public static string NomeCompletoInválidoErrorMessage {
            get {
                return ResourceManager.GetString("NomeCompletoInválidoErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "não pode estar vazio"
        /// </summary>
        public static string NotEmptyErrorMessage {
            get {
                return ResourceManager.GetString("NotEmptyErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha tem mais que {MinimunLength} caracteres"
        /// </summary>
        public static string PasswordMaximunLengthErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMaximunLengthErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha tem menos que {MinimunLength} caracteres"
        /// </summary>
        public static string PasswordMinimunLengthErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinimunLengthErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Português"
        /// </summary>
        public static string Português {
            get {
                return ResourceManager.GetString("Português", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha precisa conter um digito"
        /// </summary>
        public static string RequireDigitErrorMessage {
            get {
                return ResourceManager.GetString("RequireDigitErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha precisa conter uma letra"
        /// </summary>
        public static string RequireLetterErrorMessage {
            get {
                return ResourceManager.GetString("RequireLetterErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha precisa conter uma letra minúscula"
        /// </summary>
        public static string RequireLowercaseLetterErrorMessage {
            get {
                return ResourceManager.GetString("RequireLowercaseLetterErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha precisa conter um simbolo"
        /// </summary>
        public static string RequireSymbolErrorMessage {
            get {
                return ResourceManager.GetString("RequireSymbolErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Senha precisa conter uma letra maiúscula"
        /// </summary>
        public static string RequireUppercaseLetterErrorMessage {
            get {
                return ResourceManager.GetString("RequireUppercaseLetterErrorMessage", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to "Sigla do Pais Inválida"
        /// </summary>
        public static string SiglaDoPaisInvalida {
            get {
                return ResourceManager.GetString("SiglaDoPaisInvalida", Thread.CurrentThread.CurrentUICulture) ?? string.Empty;
            }
        }
    }

    /// <summary>
    /// Keys of all available strings in the applications resx-resources.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGenerated]
    public enum StringResourceKey
    {
        /// <summary>
        ///   Looks up a localized string similar to As senhas não sâo iguais.
        /// </summary>
        AsSenhasNãoSâoIguais,
        /// <summary>
        ///   Looks up a localized string similar to CEP Inválido.
        /// </summary>
        CEPInválido,
        /// <summary>
        ///   Looks up a localized string similar to CNPJ Inválido.
        /// </summary>
        CNPJInválido,
        /// <summary>
        ///   Looks up a localized string similar to CPF Inválido.
        /// </summary>
        CPFInválido,
        /// <summary>
        ///   Looks up a localized string similar to Data Inválida.
        /// </summary>
        DataInválidaErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to '{0}' precisa ser maior que '{1}'.
        /// </summary>
        DateTimeOffsetDateGreaterThanErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to DDD Inválido.
        /// </summary>
        DDDInvalido,
        /// <summary>
        ///   Looks up a localized string similar to Senha nao pode ter sequencia crescente (por ex.123....
        /// </summary>
        DontAllowAscendentSequenceErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha nao pode ter sequencia crescente (por ex. 32....
        /// </summary>
        DontAllowDescendentSequenceErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha nao pode conter caracteres repetidos.
        /// </summary>
        DontAllowRepeatsErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to {0} é obrigatório(a).
        /// </summary>
        éobrigatórioa,
        /// <summary>
        ///   Looks up a localized string similar to Estado Inválido.
        /// </summary>
        EstadoInvalido,
        /// <summary>
        ///   Looks up a localized string similar to Idade não permitida.
        /// </summary>
        Idadenãopermitida,
        /// <summary>
        ///   Looks up a localized string similar to Identificação.
        /// </summary>
        Identificação,
        /// <summary>
        ///   Looks up a localized string similar to Identificação é obrigatória.
        /// </summary>
        Identificaçãoéobrigatória,
        /// <summary>
        ///   Looks up a localized string similar to Idioma.
        /// </summary>
        Idioma,
        /// <summary>
        ///   Looks up a localized string similar to Idiomas.
        /// </summary>
        Idiomas,
        /// <summary>
        ///   Looks up a localized string similar to Inglês.
        /// </summary>
        Inglês,
        /// <summary>
        ///   Looks up a localized string similar to Esta opção precisa estar marcada.
        /// </summary>
        IsCheckedErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Nome Completo Inválido.
        /// </summary>
        NomeCompletoInválidoErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to não pode estar vazio.
        /// </summary>
        NotEmptyErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha tem mais que {MinimunLength} caracteres.
        /// </summary>
        PasswordMaximunLengthErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha tem menos que {MinimunLength} caracteres.
        /// </summary>
        PasswordMinimunLengthErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Português.
        /// </summary>
        Português,
        /// <summary>
        ///   Looks up a localized string similar to Senha precisa conter um digito.
        /// </summary>
        RequireDigitErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha precisa conter uma letra.
        /// </summary>
        RequireLetterErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha precisa conter uma letra minúscula.
        /// </summary>
        RequireLowercaseLetterErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha precisa conter um simbolo.
        /// </summary>
        RequireSymbolErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Senha precisa conter uma letra maiúscula.
        /// </summary>
        RequireUppercaseLetterErrorMessage,
        /// <summary>
        ///   Looks up a localized string similar to Sigla do Pais Inválida.
        /// </summary>
        SiglaDoPaisInvalida,
    }

    /// <summary>
    /// Specifies a localized description for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedDescriptionAttribute : System.ComponentModel.DescriptionAttribute
    {
        private readonly string _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedDescriptionAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedDescriptionAttribute(StringResourceKey resourceKey)
        {
            _resourceKey = resourceKey.ToString();
        }

        /// <summary>
        /// Gets the localized description from the resource id stored in this attribute.
        /// </summary>
        public override string Description
        {
            get
            {
                return SharedResources.ResourceManager.GetString(_resourceKey);
            }
        }
    }

    /// <summary>
    /// Specifies a localized display name for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedDisplayNameAttribute : System.ComponentModel.DisplayNameAttribute
    {
        private readonly string _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedDisplayNameAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedDisplayNameAttribute(StringResourceKey resourceKey)
        {
            _resourceKey = resourceKey.ToString();
        }

        /// <summary>
        /// Gets the localized display name from the resource id stored in this attribute.
        /// </summary>
        public override string DisplayName
        {
            get
            {
                return SharedResources.ResourceManager.GetString(_resourceKey);
            }
        }
    }

    /// <summary>
    /// Specifies a localized category for an object.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.All, AllowMultiple=false)]
    public sealed class LocalizedCategoryAttribute : System.ComponentModel.CategoryAttribute
    {
        /// <summary>
        /// Initializes a new instance of the <see cref="LocalizedCategoryAttribute"/> class.
        /// </summary>
        /// <param name="resourceKey">The resource key of the associated resource.</param>
        public LocalizedCategoryAttribute(StringResourceKey resourceKey)
            : base(resourceKey.ToString())
        {
        }

        /// <summary>
        /// Gets the localized category name from the resource id stored in this attribute.
        /// </summary>
        protected override string GetLocalizedString(string value)
        {
            return SharedResources.ResourceManager.GetString(value);
        }
    }

    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.DataTypeAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class DataTypeAttribute : System.ComponentModel.DataAnnotations.DataTypeAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTypeAttribute"/> class.
        /// </summary>
        public DataTypeAttribute(StringResourceKey resourceKey, System.ComponentModel.DataAnnotations.DataType dataType)
            : base(dataType)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="DataTypeAttribute"/> class.
        /// </summary>
        public DataTypeAttribute(StringResourceKey resourceKey, string customDataType)
            : base(customDataType)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(SharedResources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.RangeAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class RangeAttribute : System.ComponentModel.DataAnnotations.RangeAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="RangeAttribute"/> class.
        /// </summary>
        public RangeAttribute(StringResourceKey resourceKey, int minimum, int maximum)
            : base(minimum, maximum)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RangeAttribute"/> class.
        /// </summary>
        public RangeAttribute(StringResourceKey resourceKey, double minimum, double maximum)
            : base(minimum, maximum)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Initializes a new instance of the <see cref="RangeAttribute"/> class.
        /// </summary>
        public RangeAttribute(StringResourceKey resourceKey, Type type, string minimum, string maximum)
            : base(type, minimum, maximum)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(SharedResources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.RegularExpressionAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class RegularExpressionAttribute : System.ComponentModel.DataAnnotations.RegularExpressionAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="RegularExpressionAttribute"/> class.
        /// </summary>
        public RegularExpressionAttribute(StringResourceKey resourceKey, string pattern)
            : base(pattern)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(SharedResources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.RequiredAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class RequiredAttribute : System.ComponentModel.DataAnnotations.RequiredAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="RequiredAttribute"/> class.
        /// </summary>
        public RequiredAttribute(StringResourceKey resourceKey)
            : base()
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(SharedResources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    
    /// <summary>
    /// A localizable version of the <see cref="System.ComponentModel.DataAnnotations.StringLengthAttribute"/> class.
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCode("ResXResourceManager", "1.0.0.0")]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [AttributeUsage(AttributeTargets.Field | AttributeTargets.Parameter | AttributeTargets.Property, AllowMultiple = false)]
    public class StringLengthAttribute : System.ComponentModel.DataAnnotations.StringLengthAttribute
    {
        private StringResourceKey _resourceKey;

        /// <summary>
        /// Initializes a new instance of the <see cref="StringLengthAttribute"/> class.
        /// </summary>
        public StringLengthAttribute(StringResourceKey resourceKey, int maximumLength)
            : base(maximumLength)
        {
            ResourceKey = resourceKey;
        }

        /// <summary>
        /// Gets or sets the resource key.
        /// </summary>
        public StringResourceKey ResourceKey
        {
            get
            {
                return _resourceKey;
            }
            set
            {
                _resourceKey = value;
                ErrorMessageResourceType = typeof(SharedResources);
                ErrorMessageResourceName = value.ToString();
            }
        }
    }
    

}
