//------------------------------------------------------------------------------
// <auto-generated>
//     O código foi gerado por uma ferramenta.
//     Versão de Tempo de Execução:4.0.30319.42000
//
//     As alterações ao arquivo poderão causar comportamento incorreto e serão perdidas se
//     o código for gerado novamente.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CBT.DataAnnotations.Resources {
    using System;
    
    
    /// <summary>
    ///   Uma classe de recurso de tipo de alta segurança, para pesquisar cadeias de caracteres localizadas etc.
    /// </summary>
    // Essa classe foi gerada automaticamente pela classe StronglyTypedResourceBuilder
    // através de uma ferramenta como ResGen ou Visual Studio.
    // Para adicionar ou remover um associado, edite o arquivo .ResX e execute ResGen novamente
    // com a opção /str, ou recrie o projeto do VS.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public partial class SharedResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SharedResources() {
        }
        
        /// <summary>
        ///   Retorna a instância de ResourceManager armazenada em cache usada por essa classe.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CBT.DataAnnotations.Resources.SharedResources", typeof(SharedResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Substitui a propriedade CurrentUICulture do thread atual para todas as
        ///   pesquisas de recursos que usam essa classe de recurso de tipo de alta segurança.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a As senhas não sâo iguais.
        /// </summary>
        public static string AsSenhasNãoSâoIguais {
            get {
                return ResourceManager.GetString("AsSenhasNãoSâoIguais", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CEP Inválido.
        /// </summary>
        public static string CEPInválido {
            get {
                return ResourceManager.GetString("CEPInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CNPJ Inválido.
        /// </summary>
        public static string CNPJInválido {
            get {
                return ResourceManager.GetString("CNPJInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a CPF Inválido.
        /// </summary>
        public static string CPFInválido {
            get {
                return ResourceManager.GetString("CPFInválido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Data Inválida.
        /// </summary>
        public static string DataInválidaErrorMessage {
            get {
                return ResourceManager.GetString("DataInválidaErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a &apos;{0}&apos; precisa ser maior que &apos;{1}&apos;.
        /// </summary>
        public static string DateTimeOffsetDateGreaterThanErrorMessage {
            get {
                return ResourceManager.GetString("DateTimeOffsetDateGreaterThanErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a DDD Inválido.
        /// </summary>
        public static string DDDInvalido {
            get {
                return ResourceManager.GetString("DDDInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha nao pode ter sequencia crescente (por ex.123 ou abc).
        /// </summary>
        public static string DontAllowAscendentSequenceErrorMessage {
            get {
                return ResourceManager.GetString("DontAllowAscendentSequenceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha nao pode ter sequencia crescente (por ex. 321 ou cba).
        /// </summary>
        public static string DontAllowDescendentSequenceErrorMessage {
            get {
                return ResourceManager.GetString("DontAllowDescendentSequenceErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha nao pode conter caracteres repetidos.
        /// </summary>
        public static string DontAllowRepeatsErrorMessage {
            get {
                return ResourceManager.GetString("DontAllowRepeatsErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a {0} é obrigatório(a).
        /// </summary>
        public static string éobrigatórioa {
            get {
                return ResourceManager.GetString("éobrigatórioa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Estado Inválido.
        /// </summary>
        public static string EstadoInvalido {
            get {
                return ResourceManager.GetString("EstadoInvalido", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idade não permitida.
        /// </summary>
        public static string Idadenãopermitida {
            get {
                return ResourceManager.GetString("Idadenãopermitida", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificação.
        /// </summary>
        public static string Identificação {
            get {
                return ResourceManager.GetString("Identificação", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Identificação é obrigatória.
        /// </summary>
        public static string Identificaçãoéobrigatória {
            get {
                return ResourceManager.GetString("Identificaçãoéobrigatória", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idioma.
        /// </summary>
        public static string Idioma {
            get {
                return ResourceManager.GetString("Idioma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Idiomas.
        /// </summary>
        public static string Idiomas {
            get {
                return ResourceManager.GetString("Idiomas", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Inglês.
        /// </summary>
        public static string Inglês {
            get {
                return ResourceManager.GetString("Inglês", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Esta opção precisa estar marcada.
        /// </summary>
        public static string IsCheckedErrorMessage {
            get {
                return ResourceManager.GetString("IsCheckedErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Nome Completo Inválido.
        /// </summary>
        public static string NomeCompletoInválidoErrorMessage {
            get {
                return ResourceManager.GetString("NomeCompletoInválidoErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a não pode estar vazio.
        /// </summary>
        public static string NotEmptyErrorMessage {
            get {
                return ResourceManager.GetString("NotEmptyErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha tem mais que {MinimunLength} caracteres.
        /// </summary>
        public static string PasswordMaximunLengthErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMaximunLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha tem menos que {MinimunLength} caracteres.
        /// </summary>
        public static string PasswordMinimunLengthErrorMessage {
            get {
                return ResourceManager.GetString("PasswordMinimunLengthErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Português.
        /// </summary>
        public static string Português {
            get {
                return ResourceManager.GetString("Português", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha precisa conter um digito.
        /// </summary>
        public static string RequireDigitErrorMessage {
            get {
                return ResourceManager.GetString("RequireDigitErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha precisa conter uma letra.
        /// </summary>
        public static string RequireLetterErrorMessage {
            get {
                return ResourceManager.GetString("RequireLetterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha precisa conter uma letra minúscula.
        /// </summary>
        public static string RequireLowercaseLetterErrorMessage {
            get {
                return ResourceManager.GetString("RequireLowercaseLetterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha precisa conter um simbolo.
        /// </summary>
        public static string RequireSymbolErrorMessage {
            get {
                return ResourceManager.GetString("RequireSymbolErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Senha precisa conter uma letra maiúscula.
        /// </summary>
        public static string RequireUppercaseLetterErrorMessage {
            get {
                return ResourceManager.GetString("RequireUppercaseLetterErrorMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Consulta uma cadeia de caracteres localizada semelhante a Sigla do Pais Inválida.
        /// </summary>
        public static string SiglaDoPaisInvalida {
            get {
                return ResourceManager.GetString("SiglaDoPaisInvalida", resourceCulture);
            }
        }
    }
}
