using System;
using System.Collections.Generic;
using System.Text;

namespace CastelloBranco.Singletons;

public static class BrazilAreaCode
{
    public static readonly List<PhoneAreaCode> AreaCodes = new ()
    {
        new () { AreaCode = "11",  State = "SP", Region = "Sao Paulo, São Paulo e Região Metropolitana" },
        new () { AreaCode = "12",  State = "SP", Region = "Sao Paulo, São José dos Campos/Taubaté/Vale do Paraíba" },
        new () { AreaCode = "13",  State = "SP", Region = "Sao Paulo, Santos/São Vicente/Vale do Ribeira" },
        new () { AreaCode = "14",  State = "SP", Region = "Sao Paulo, Bauru/Botucatu/Jaú/Marília" },
        new () { AreaCode = "15",  State = "SP", Region = "Sao Paulo, Itapetininga/Itapeva/Sorocaba" },
        new () { AreaCode = "16",  State = "SP", Region = "Sao Paulo, Araraquara/Franca/Ribeirão Preto/São Carlos" },
        new () { AreaCode = "17",  State = "SP", Region = "Sao Paulo, Catanduva/Barretos/São José do Rio Preto/Votuporanga" },
        new () { AreaCode = "18",  State = "SP", Region = "Sao Paulo, Presidente Prudente/Araçatuba/Birigui/Assis" },
        new () { AreaCode = "19",  State = "SP", Region = "Sao Paulo, Americana/Campinas/Limeira/Piracicaba" },
        new () { AreaCode = "21",  State = "RJ", Region = "Rio de Janeiro, Rio de Janeiro e Região Metropolitana/Teresópolis" },
        new () { AreaCode = "22",  State = "RJ", Region = "Rio de Janeiro, Cabo Frio/Campos dos Goytacazes/Macaé/Nova Friburgo" },
        new () { AreaCode = "24",  State = "RJ", Region = "Rio de Janeiro, Angra dos Reis/Petrópolis/Volta Redonda" },
        new () { AreaCode = "27",  State = "ES", Region = "Espirito Santo,Vitória e Região Metropolitana/Colatina/Domingos Martins/Linhares" },
        new () { AreaCode = "28",  State = "ES", Region = "Espirito Santo, Cachoeiro de Itapemirim/Castelo/Marataízes" },
        new () { AreaCode = "31",  State = "MG", Region = "Minas Gerais, Belo Horizonte e Região Metropolitana/Ipatinga" },
        new () { AreaCode = "32",  State = "MG", Region = "Minas Gerais, Juiz de Fora/São João del-Rei/Barbacena" },
        new () { AreaCode = "33",  State = "MG", Region = "Minas Gerais, Governador Valadares/Teófilo Otoni/Caratinga/Manhuaçu" },
        new () { AreaCode = "34",  State = "MG", Region = "Minas Gerais, Araguari/Uberlândia/Uberaba" },
        new () { AreaCode = "35",  State = "MG", Region = "Minas Gerais, Poços de Caldas/Pouso Alegre/Varginha" },
        new () { AreaCode = "36",  State = "MG", Region = "Minas Gerais, Gurinhata" },
        new () { AreaCode = "37",  State = "MG", Region = "Minas Gerais, Divinópolis/Itaúna" },
        new () { AreaCode = "38",  State = "MG", Region = "Minas Gerais, Diamantina/Montes Claros/Unaí" },
        new () { AreaCode = "39",  State = "MG", Region = "Minas Gerais, Couto de Magalhães de Minas/Aricanduva/Veredinha" },
        new () { AreaCode = "41",  State = "PR", Region = "Paraná, Curitiba e Região Metropolitana" },
        new () { AreaCode = "42",  State = "PR", Region = "Paraná, Ponta Grossa/Guarapuava" },
        new()  { AreaCode = "43",  State = "PR", Region = "Paraná, Apucarana/Londrina" },
        new () { AreaCode = "44",  State = "PR", Region = "Paraná Maringá/Campo Mourão/Umuarama" },
        new () { AreaCode = "45",  State = "PR", Region = "Paraná, Cascavel/Foz do Iguaçu" },
        new () { AreaCode = "46",  State = "PR", Region = "Paraná Francisco Beltrão/Pato Branco" },
        new () { AreaCode = "47",  State = "SC", Region = "Santa Catarina, Balneário Camboriú/Blumenau/Itajaí/Joinville" },
        new () { AreaCode = "48",  State = "SC", Region = "Santa Catarina, Florianópolis e Região Metropolitana/Criciúma" },
        new () { AreaCode = "49",  State = "SC", Region = "Santa Catarina, Caçador/Chapecó/Lages" },
        new () { AreaCode = "51",  State = "RS", Region = "Rio Grande do Sul, Porto Alegre e Região Metropolitana/Santa Cruz do Sul/Litoral Norte" },
        new () { AreaCode = "52",  State = "RS", Region = "Rio Grande do Sul, Pelotas/Rio Grande" },
        new () { AreaCode = "53",  State = "RS", Region = "Rio Grande do Sul, Aceguá/Arroio Grande/Bagé" },
        new () { AreaCode = "54",  State = "RS", Region = "Rio Grande do Sul, Caxias do Sul/Passo Fundo" },
        new () { AreaCode = "55",  State = "RS", Region = "Rio Grande do Sul, Santa Maria/Santana do Livramento/Santo Ângelo/Uruguaiana" },
        new () { AreaCode = "61",  State = "GO", Region = "Brasília, Distrito Federal/Goiás Abrangência em todo o Distrito Federal e municípios da Região Integrada de Desenvolvimento do Distrito Federal e Entorno" },
        new () { AreaCode = "62",  State = "GO", Region = "Goiás, Goiânia e Região Metropolitana/Anápolis/Niquelândia/Porangatu" },
        new  (){ AreaCode = "63",  State = "TO", Region = "Tocantins, Abrangência em todo o estado" },
        new()  { AreaCode = "64",  State = "GO", Region = "Goiás, Caldas Novas/Catalão/Itumbiara/Rio Verde" },
        new  (){ AreaCode = "65",  State = "MT", Region = "Mato Grosso, Cuiabá e Região Metropolitana" },
        new  (){ AreaCode = "66",  State = "MT", Region = "Mato Grosso, Rondonópolis/Sinop" },
        new () { AreaCode = "67",  State = "MS", Region = "Mato Grosso do Sul, Abrangência em todo o estado" },
        new () { AreaCode = "68",  State = "AC", Region = "Acre, Abrangência em todo o estado" },
        new () { AreaCode = "69",  State = "RO", Region = "Rondônia, Abrangência em todo o estado" },
        new () { AreaCode = "71",  State = "BA", Region = "Bahia, Salvador e Região Metropolitana" },
        new () { AreaCode = "73",  State = "BA", Region = "Bahia, Ilhéus/Itabuna" },
        new () { AreaCode = "74",  State = "BA", Region = "Bahia, Juazeiro/Irecê" },
        new () { AreaCode = "75",  State = "BA", Region = "Bahia, Feira de Santana/Alagoinhas" },
        new () { AreaCode = "77",  State = "BA", Region = "Bahia, Vitória da Conquista/Barreiras" },
        new () { AreaCode = "79",  State = "SE", Region = "Sergipe, Abrangência em todo o estado" },
        new () { AreaCode = "81",  State = "PE", Region = "Pernambuco, Recife e Região Metropolitana/Caruaru" },
        new () { AreaCode = "82",  State = "AL", Region = "Alagoas, Abrangência em todo o estado" },
        new () { AreaCode = "83",  State = "PB", Region = "Paraíba, Abrangência em todo o estado" },
        new  (){ AreaCode = "84",  State = "RN", Region = "Rio Grande do Norte Abrangência em todo o estado" },
        new  (){ AreaCode = "85",  State = "CE", Region = "Ceará, Fortaleza e Região Metropolitana" },
        new () { AreaCode = "86",  State = "PI", Region = "Piauí, Teresina e Região Metropolitana/Parnaíba" },
        new () { AreaCode = "87",  State = "PE", Region = "Pernambuco Garanhuns/Petrolina/Salgueiro/Serra Talhada" },
        new () { AreaCode = "88",  State = "CE", Region = "Ceará, Juazeiro do Norte/Sobral" },
        new () { AreaCode = "89",  State = "PI", Region = "Piauí, Picos/Floriano" },
        new () { AreaCode = "91",  State = "PA", Region = "Pará, Belém e Região Metropolitana" },
        new () { AreaCode = "92",  State = "AM", Region = "Amazonas, Manaus e Região Metropolitana/Parintins" },
        new  (){ AreaCode = "93",  State = "PA", Region = "Pará, Santarém/Altamira" },
        new  (){ AreaCode = "94",  State = "PA", Region = "Pará, Marabá" },
        new () { AreaCode = "95",  State = "RR", Region = "Roraima, Abrangência em todo o estado" },
        new  (){ AreaCode = "96",  State = "AP", Region = "Amapá, Abrangência em todo o estado" },
        new  (){ AreaCode = "97",  State = "AM", Region = "Amazonas Abrangência no interior do estado" },
        new () { AreaCode = "98",  State = "MA", Region = "Maranhão, São Luís e Região Metropolitana" },
        new () { AreaCode = "99",  State = "MA", Region = "Maranhão Caxias/Codó/Imperatriz" }
    };
}
