using System;
using System.Collections.Generic;
using System.Text;

namespace CBT.Singletons;

public static class DDDsDoBrasil
{
    public static readonly List<Regiao_ddd> DDDs = new ()
    {
        new () { Ddd = "11",  Estado = "SP", Regiao = "Sao Paulo, São Paulo e Região Metropolitana" },
        new () { Ddd = "12",  Estado = "SP", Regiao = "Sao Paulo, São José dos Campos/Taubaté/Vale do Paraíba" },
        new () { Ddd = "13",  Estado = "SP", Regiao = "Sao Paulo, Santos/São Vicente/Vale do Ribeira" },
        new () { Ddd = "14",  Estado = "SP", Regiao = "Sao Paulo, Bauru/Botucatu/Jaú/Marília" },
        new () { Ddd = "15",  Estado = "SP", Regiao = "Sao Paulo, Itapetininga/Itapeva/Sorocaba" },
        new () { Ddd = "16",  Estado = "SP", Regiao = "Sao Paulo, Araraquara/Franca/Ribeirão Preto/São Carlos" },
        new () { Ddd = "17",  Estado = "SP", Regiao = "Sao Paulo, Catanduva/Barretos/São José do Rio Preto/Votuporanga" },
        new () { Ddd = "18",  Estado = "SP", Regiao = "Sao Paulo, Presidente Prudente/Araçatuba/Birigui/Assis" },
        new () { Ddd = "19",  Estado = "SP", Regiao = "Sao Paulo, Americana/Campinas/Limeira/Piracicaba" },
        new () { Ddd = "21",  Estado = "RJ", Regiao = "Rio de Janeiro, Rio de Janeiro e Região Metropolitana/Teresópolis" },
        new () { Ddd = "22",  Estado = "RJ", Regiao = "Rio de Janeiro, Cabo Frio/Campos dos Goytacazes/Macaé/Nova Friburgo" },
        new () { Ddd = "24",  Estado = "RJ", Regiao = "Rio de Janeiro, Angra dos Reis/Petrópolis/Volta Redonda" },
        new () { Ddd = "27",  Estado = "ES", Regiao = "Espirito Santo,Vitória e Região Metropolitana/Colatina/Domingos Martins/Linhares" },
        new () { Ddd = "28",  Estado = "ES", Regiao = "Espirito Santo, Cachoeiro de Itapemirim/Castelo/Marataízes" },
        new () { Ddd = "31",  Estado = "MG", Regiao = "Minas Gerais, Belo Horizonte e Região Metropolitana/Ipatinga" },
        new () { Ddd = "32",  Estado = "MG", Regiao = "Minas Gerais, Juiz de Fora/São João del-Rei/Barbacena" },
        new () { Ddd = "33",  Estado = "MG", Regiao = "Minas Gerais, Governador Valadares/Teófilo Otoni/Caratinga/Manhuaçu" },
        new () { Ddd = "34",  Estado = "MG", Regiao = "Minas Gerais, Araguari/Uberlândia/Uberaba" },
        new () { Ddd = "35",  Estado = "MG", Regiao = "Minas Gerais, Poços de Caldas/Pouso Alegre/Varginha" },
        new () { Ddd = "36",  Estado = "MG", Regiao = "Minas Gerais, Gurinhata" },
        new () { Ddd = "37",  Estado = "MG", Regiao = "Minas Gerais, Divinópolis/Itaúna" },
        new () { Ddd = "38",  Estado = "MG", Regiao = "Minas Gerais, Diamantina/Montes Claros/Unaí" },
        new () { Ddd = "39",  Estado = "MG", Regiao = "Minas Gerais, Couto de Magalhães de Minas/Aricanduva/Veredinha" },
        new () { Ddd = "41",  Estado = "PR", Regiao = "Paraná, Curitiba e Região Metropolitana" },
        new () { Ddd = "42",  Estado = "PR", Regiao = "Paraná, Ponta Grossa/Guarapuava" },
        new()  { Ddd = "43",  Estado = "PR", Regiao = "Paraná, Apucarana/Londrina" },
        new () { Ddd = "44",  Estado = "PR", Regiao = "Paraná Maringá/Campo Mourão/Umuarama" },
        new () { Ddd = "45",  Estado = "PR", Regiao = "Paraná, Cascavel/Foz do Iguaçu" },
        new () { Ddd = "46",  Estado = "PR", Regiao = "Paraná Francisco Beltrão/Pato Branco" },
        new () { Ddd = "47",  Estado = "SC", Regiao = "Santa Catarina, Balneário Camboriú/Blumenau/Itajaí/Joinville" },
        new () { Ddd = "48",  Estado = "SC", Regiao = "Santa Catarina, Florianópolis e Região Metropolitana/Criciúma" },
        new () { Ddd = "49",  Estado = "SC", Regiao = "Santa Catarina, Caçador/Chapecó/Lages" },
        new () { Ddd = "51",  Estado = "RS", Regiao = "Rio Grande do Sul, Porto Alegre e Região Metropolitana/Santa Cruz do Sul/Litoral Norte" },
        new () { Ddd = "52",  Estado = "RS", Regiao = "Rio Grande do Sul, Pelotas/Rio Grande" },
        new () { Ddd = "53",  Estado = "RS", Regiao = "Rio Grande do Sul, Aceguá/Arroio Grande/Bagé" },
        new () { Ddd = "54",  Estado = "RS", Regiao = "Rio Grande do Sul, Caxias do Sul/Passo Fundo" },
        new () { Ddd = "55",  Estado = "RS", Regiao = "Rio Grande do Sul, Santa Maria/Santana do Livramento/Santo Ângelo/Uruguaiana" },
        new () { Ddd = "61",  Estado = "GO", Regiao = "Brasília, Distrito Federal/Goiás Abrangência em todo o Distrito Federal e municípios da Região Integrada de Desenvolvimento do Distrito Federal e Entorno" },
        new () { Ddd = "62",  Estado = "GO", Regiao = "Goiás, Goiânia e Região Metropolitana/Anápolis/Niquelândia/Porangatu" },
        new  (){ Ddd = "63",  Estado = "TO", Regiao = "Tocantins, Abrangência em todo o estado" },
        new()  { Ddd = "64",  Estado = "GO", Regiao = "Goiás, Caldas Novas/Catalão/Itumbiara/Rio Verde" },
        new  (){ Ddd = "65",  Estado = "MT", Regiao = "Mato Grosso, Cuiabá e Região Metropolitana" },
        new  (){ Ddd = "66",  Estado = "MT", Regiao = "Mato Grosso, Rondonópolis/Sinop" },
        new () { Ddd = "67",  Estado = "MS", Regiao = "Mato Grosso do Sul, Abrangência em todo o estado" },
        new () { Ddd = "68",  Estado = "AC", Regiao = "Acre, Abrangência em todo o estado" },
        new () { Ddd = "69",  Estado = "RO", Regiao = "Rondônia, Abrangência em todo o estado" },
        new () { Ddd = "71",  Estado = "BA", Regiao = "Bahia, Salvador e Região Metropolitana" },
        new () { Ddd = "73",  Estado = "BA", Regiao = "Bahia, Ilhéus/Itabuna" },
        new () { Ddd = "74",  Estado = "BA", Regiao = "Bahia, Juazeiro/Irecê" },
        new () { Ddd = "75",  Estado = "BA", Regiao = "Bahia, Feira de Santana/Alagoinhas" },
        new () { Ddd = "77",  Estado = "BA", Regiao = "Bahia, Vitória da Conquista/Barreiras" },
        new () { Ddd = "79",  Estado = "SE", Regiao = "Sergipe, Abrangência em todo o estado" },
        new () { Ddd = "81",  Estado = "PE", Regiao = "Pernambuco, Recife e Região Metropolitana/Caruaru" },
        new () { Ddd = "82",  Estado = "AL", Regiao = "Alagoas, Abrangência em todo o estado" },
        new () { Ddd = "83",  Estado = "PB", Regiao = "Paraíba, Abrangência em todo o estado" },
        new  (){ Ddd = "84",  Estado = "RN", Regiao = "Rio Grande do Norte Abrangência em todo o estado" },
        new  (){ Ddd = "85",  Estado = "CE", Regiao = "Ceará, Fortaleza e Região Metropolitana" },
        new () { Ddd = "86",  Estado = "PI", Regiao = "Piauí, Teresina e Região Metropolitana/Parnaíba" },
        new () { Ddd = "87",  Estado = "PE", Regiao = "Pernambuco Garanhuns/Petrolina/Salgueiro/Serra Talhada" },
        new () { Ddd = "88",  Estado = "CE", Regiao = "Ceará, Juazeiro do Norte/Sobral" },
        new () { Ddd = "89",  Estado = "PI", Regiao = "Piauí, Picos/Floriano" },
        new () { Ddd = "91",  Estado = "PA", Regiao = "Pará, Belém e Região Metropolitana" },
        new () { Ddd = "92",  Estado = "AM", Regiao = "Amazonas, Manaus e Região Metropolitana/Parintins" },
        new  (){ Ddd = "93",  Estado = "PA", Regiao = "Pará, Santarém/Altamira" },
        new  (){ Ddd = "94",  Estado = "PA", Regiao = "Pará, Marabá" },
        new () { Ddd = "95",  Estado = "RR", Regiao = "Roraima, Abrangência em todo o estado" },
        new  (){ Ddd = "96",  Estado = "AP", Regiao = "Amapá, Abrangência em todo o estado" },
        new  (){ Ddd = "97",  Estado = "AM", Regiao = "Amazonas Abrangência no interior do estado" },
        new () { Ddd = "98",  Estado = "MA", Regiao = "Maranhão, São Luís e Região Metropolitana" },
        new () { Ddd = "99",  Estado = "MA", Regiao = "Maranhão Caxias/Codó/Imperatriz" }
    };
}
