using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Text;

namespace CastelloBranco.Singletons;

public static class PaisesDoMundo
{
    public static List<Pais> Paises = new List<Pais>()
    {
            new Pais () { Nome = "AFEGANISTÃO",                              Sigla = "AF",           Ddi = "+93",             Continente = "ASIA" },
            new Pais () { Nome = "ÁFRICA DO SUL",                            Sigla = "ZA",           Ddi ="+27",              Continente = "AFRICA" },
            new Pais () { Nome = "ALBÂNIA",                                  Sigla = "AL",           Ddi = "+355",            Continente = "EUROPA" },
            new Pais () { Nome = "ALEMANHA",                                 Sigla = "DE",           Ddi = "+49",             Continente = "EUROPA" },
            new Pais () { Nome = "ANDORRA",                                  Sigla = "AD",           Ddi = "+376",            Continente = "EUROPA" },
            new Pais () { Nome = "ANGOLA",                                   Sigla = "AO",           Ddi = "+244",            Continente = "AFRICA" },
            new Pais () { Nome = "ANGUILLA",                                 Sigla = "AI",           Ddi = "+1",              Continente = "AMERICA CENTRAL" },
            new Pais () { Nome = "REPÚBLICA DA MACEDÔNIA",                   Sigla = "MK",           Ddi = "+389",            Continente = "EUROPA" },
            new Pais () { Nome = "ANTÍGUA E BARBUDA",                        Sigla = "AG",           Ddi = "+1",              Continente = "AMERICA CENTRAL" },
            new Pais () { Nome = "ANTILHAS HOLANDESAS",                      Sigla = "AN",           Ddi = "+599",            Continente = "AMERICA CENTRAL" },
            new Pais () { Nome = "ARÁBIA SAUDITA",                           Sigla = "SA",           Ddi = "+966",            Continente = "ASIA" },
            new Pais () { Nome = "ARGÉLIA",                                  Sigla = "DZ",           Ddi = "+213",            Continente = "AFRICA" },
            new Pais () { Nome = "ARGENTINA",                                Sigla = "AR",           Ddi = "+54",             Continente = "AMERICA DO SUL" },
            new Pais () { Nome = "ARMÊNIA",                                  Sigla = "AM",           Ddi = "+374",            Continente = "ASIA" },
            new Pais () { Nome = "ARUBA",                                    Sigla = "AW",           Ddi = "+297",            Continente = "AMERICA DO SUL" },
            new Pais () { Nome = "ASCENSAO",                                 Sigla = "SH",           Ddi = "+247",            Continente = "AFRICA" },
            new Pais () { Nome = "AUSTRÁLIA",                                Sigla = "AU",           Ddi = "+61",             Continente = "OCEANIA" },
            new Pais () { Nome = "ÁUSTRIA",                                  Sigla = "AT",           Ddi = "+43",             Continente = "EUROPA" },
            new Pais () { Nome = "ARZEBAIDJÃO",                              Sigla = "AZ",           Ddi = "+994",            Continente = "ASIA" },
            new Pais () { Nome = "BAHAMAS",                                  Sigla = "BS",           Ddi = "+1",               Continente = "AMERICA CENTRAL" },
            new Pais () { Nome = "BANGLADESH",                               Sigla = "BD",           Ddi = "+880",             Continente = "ASIA" },
            new Pais () { Nome = "BARBADOS",                                 Sigla = "BB",           Ddi = "+1",               Continente = "AMERICA CENTRAL" },
            new Pais () { Nome = "BAREINE",                                  Sigla = "BH",           Ddi = "+973",             Continente = "ASIA" },
            new Pais () { Nome = "BELARUS",                                  Sigla = "BY",           Ddi = "+375",             Continente = "EUROPA" },
            new Pais () { Nome = "BÉLGICA",                                  Sigla = "BE",           Ddi = "+32",              Continente = "EUROPA" },
            new Pais () { Nome = "BELIZE",                                   Sigla = "BZ",           Ddi = "+501",             Continente = "AMERICA CENTRAL" },
            new Pais () { Nome = "BENIN",                                    Sigla = "BJ",           Ddi = "+229",             Continente = "AFRICA" },
            new Pais () { Nome = "BERMUDAS",                                 Sigla = "BM",           Ddi = "+1",               Continente = "AMERICA CENTRAL" },
            new Pais () { Nome = "BOLÍVIA",                                  Sigla = "BO",           Ddi = "+591",             Continente = "AMERICA DO SUL" },
            new Pais () { Nome = "BÓSNIA E HERZEGÓVINA",                     Sigla = "BA",           Ddi = "+387",             Continente = "EUROPA" },
            new Pais () { Nome = "BOTSWANA",                                 Sigla = "BW",           Ddi = "+267",             Continente = "AFRICA" },
            new Pais () { Nome = "BRASIL",                                   Sigla = "BR",           Ddi = "+55",              Continente = "AMERICA DO SUL" },
            new Pais () { Nome = "BRUNEI DARUSSALAM",                        Sigla = "BN",           Ddi = "+673",             Continente = "ASIA" },
            new Pais () { Nome = "BULGÁRIA",                                 Sigla = "BG",           Ddi = "+359",             Continente = "EUROPA" },
            new Pais () { Nome = "BURKINA FASO",                             Sigla = "BF",           Ddi = "+226",             Continente = "AFRICA" },
            new Pais () { Nome = "BURUNDI",                                  Sigla = "BI",           Ddi = "+257",             Continente = "AFRICA" },
            new Pais () { Nome = "BUTÃO",                                    Sigla = "BT",           Ddi = "+975",             Continente = "ASIA" },
            new Pais () { Nome = "CABO VERDE",                               Sigla = "CV",           Ddi = "+238",             Continente = "AFRICA" },
            new Pais () { Nome = "CAMARÕES",                                 Sigla = "CM",           Ddi = "+237",             Continente = "AFRICA" },
            new Pais () { Nome = "CAMBOJA",                                  Sigla = "KH",           Ddi = "+855",             Continente = "ASIA" },
            new Pais () { Nome =  "CANADÁ",                                  Sigla = "CA",           Ddi = "+1",               Continente = "AMERICA DO NORTE" },
            new Pais () { Nome =  "CATAR",                                   Sigla = "QA",           Ddi = "+974",             Continente = "ASIA" },
            new Pais () { Nome =  "CAZAQUISTÃO",                             Sigla = "KZ",           Ddi = "+7",               Continente = "ASIA" },
            new Pais () { Nome =  "CHADE",                                   Sigla = "TD",           Ddi = "+237",             Continente = "AFRICA" },
            new Pais () { Nome =  "CHILE",                                   Sigla = "CL",           Ddi = "+56",              Continente = "AMERICA DO SUL" },
            new Pais () { Nome =  "CHINA",                                   Sigla = "CN",           Ddi = "+86",              Continente = "ASIA" },
            new Pais () { Nome =  "CHIPRE",                                  Sigla = "CY",           Ddi = " +357",            Continente = "EUROPA" },
            new Pais () { Nome =  "COLÔMBIA",                                Sigla = "CO",           Ddi = "+57",              Continente = "AMERICA DO SUL" },
            new Pais () { Nome =  "COMORES",                                 Sigla = "KM",           Ddi = "+269",             Continente = "AFRICA" },
            new Pais () { Nome =  "CONGO BRAZAVILE",                         Sigla = "CG",           Ddi = "+242",             Continente = "AFRICA" },
            new Pais () { Nome =  "CONGO KINSHASA",                          Sigla = "CD",           Ddi = "+243",             Continente = "AFRICA" },
            new Pais () {  Nome = "COREIA DO NORTE",                         Sigla = "KP",           Ddi = "+850",             Continente = "ASIA" },
            new Pais () {  Nome = "COREIA DO SUL",                           Sigla = "KR",           Ddi = "+882",             Continente = "ASIA" },
            new Pais () { Nome =  "COSTA DO MARFIM",                         Sigla = "CI",           Ddi = "+225",             Continente = "AFRICA" },
            new Pais () { Nome =  "COSTA RICA",                              Sigla = "CR",           Ddi = "+506",             Continente = "AMERICA CENTRAL" },
            new Pais () { Nome =  "CROÁCIA",                                 Sigla = "HR",           Ddi = "+385",             Continente = "EUROPA" },
            new Pais () { Nome =  "CUBA",                                    Sigla = "CU",           Ddi = "+53",              Continente = "AMERICA CENTRAL" },
            new Pais () { Nome =  "DINAMARCA",                               Sigla = "DK",           Ddi = "+45",              Continente = "EUROPA" },
            new Pais () { Nome =  "DJIBUTI",                                 Sigla = "DJ",           Ddi = "+253",             Continente = "AFRICA" },
            new Pais () { Nome =  "DOMINICA",                                Sigla = "DM",           Ddi = "+1",               Continente = "AMERICA CENTRAL" },
            new Pais () { Nome =  "EGITO",                                   Sigla = "EG",           Ddi = "+20",              Continente = "AFRICA" },
            new Pais () { Nome =  "EL SALVADOR",                             Sigla = "SV",           Ddi = "+503",             Continente = "AMERICA CENTRAL" },
            new Pais () { Nome =  "EMIRADOS ÁRABES UNIDOS",                  Sigla = "AE",           Ddi = "+971",             Continente = "AFRICA" },
            new Pais () { Nome =  "EQUADOR",                                 Sigla = "EC",           Ddi = "+593",             Continente = "AMERICA DO SUL" },
            new Pais () { Nome =  "ERITRÉIA",                                Sigla = "ER",           Ddi = "+291",             Continente = "AFRICA" },
            new Pais () { Nome =  "ESLOVÁQUIA",                              Sigla = "SK",           Ddi = "+421",             Continente = "EUROPA" },
            new Pais () { Nome =  "ESLOVÊNIA",                               Sigla = "SI",           Ddi = "+386",             Continente = "EUROPA" },
            new Pais () { Nome =  "ESPANHA",                                 Sigla = "ES",           Ddi = "+34",              Continente = "EUROPA" },
            new Pais () { Nome =  "ESTADOS UNIDOS DA AMÉRICA",               Sigla = "US",           Ddi = "+1",               Continente = "AMERICA DO NORTE" },
            new Pais () { Nome =  "ESTÔNIA",                                 Sigla = "EE",           Ddi = "+372",             Continente = "EUROPA" },
            new Pais () {  Nome = "ETIÓPIA",                                 Sigla = "ET",           Ddi = "+251",             Continente = "AFRICA" },
            new Pais () {  Nome = "FIJI",                                    Sigla = "FJ",           Ddi = "+679",             Continente = "OCEANIA" },
            new Pais () {  Nome = "FILIPINAS",                               Sigla = "PH",           Ddi = "+63",              Continente = "ASIA" },
            new Pais () {  Nome = "FINLÂNDIA",                               Sigla="FI",             Ddi = "+358",             Continente = "EUROPA" },
            new Pais () {  Nome = "FRANÇA",                                  Sigla="FR",             Ddi = "+33",              Continente = "EUROPA" },
            new Pais () {  Nome = "GABÃO",                                   Sigla = "GA",           Ddi = "+241",             Continente = "AFRICA" },
            new Pais () {  Nome = "GÂMBIA",                                  Sigla = "GM",           Ddi = "+220",             Continente = "AFRICA" },
            new Pais () {  Nome = "GANA",                                    Sigla = "GH",           Ddi = "+233",             Continente = "AFRICA" },
            new Pais () {  Nome = "GEÓRGIA",                                 Sigla = "GE",           Ddi = "+995",             Continente = "ASIA" },
            new Pais () {  Nome = "GEÓRGIA DO SUL E ILHAS SANDWICH DO SUL",  Sigla = "GS",           Ddi = "+500",             Continente = "AMERICA DO SUL" },
            new Pais () {  Nome = "GIBRALTAR",                               Sigla = "GI",           Ddi = "+350",             Continente = "EUROPA" },
            new Pais () {  Nome = "GRANADA",                                 Sigla = "GD",           Ddi = "+1",               Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "GRÉCIA",                                  Sigla = "GR",           Ddi = "+30",              Continente = "EUROPA" },
            new Pais () {  Nome = "GROELÂNDIA",                              Sigla = "GL",           Ddi = "+299",             Continente = "AMERICA DO NORTE" },
            new Pais ()  { Nome = "GUADALUPE",                               Sigla = "GP",           Ddi = "+590",             Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "GUAM",                                    Sigla = "GU",           Ddi = "+671",             Continente = "OCEANIA" },
            new Pais () {  Nome = "GUATEMALA",                               Sigla = "GT",           Ddi = "+502",             Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "GUERNSEY",                                Sigla = "GG",           Ddi = "+44",              Continente = "EUROPA" },
            new Pais () {  Nome = "GUIANA",                                  Sigla = "GY",           Ddi = "+592",             Continente = "AMERICA DO SUL" },
            new Pais () {  Nome = "GUIANA FRANCESA",                         Sigla = "GF",           Ddi = "+594",             Continente = "AMERICA DO SUL" },
            new Pais () {  Nome = "GUINÉ",                                  Sigla = "GN",            Ddi = "+224",             Continente = "AFRICA" },
            new Pais () {  Nome = "GUINÉ BISSAU",                           Sigla = "GW",            Ddi = "+245",             Continente = "AFRICA" },
            new Pais () {  Nome = "GUINÉ EQUATORIAL",                       Sigla = "GQ",            Ddi = "+240",             Continente = "AFRICA" },
            new Pais () {  Nome =  "HAITI",                                 Sigla = "HT",            Ddi = "+509",             Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "HOLANDA",                                Sigla = "NL",            Ddi = "+31",              Continente = "EUROPA" },
            new Pais () {  Nome = "HONDURAS",                               Sigla = "HN",            Ddi = "+504",               Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "HONG-KONG",                              Sigla = "HK",            Ddi = "+852",               Continente = "ASIA" },
            new Pais () {  Nome = "HUNGRIA",                                Sigla = "HU",            Ddi = "+36",                Continente = "EUROPA" },
            new Pais () {  Nome = "IÊMEN",                                  Sigla = "YE",            Ddi = "+967",               Continente = "IEMEN" },
            new Pais () {  Nome = "ILHA BOUVET",                            Sigla = "BV",            Ddi = "+47",                Continente = "ANTARTIDA" },
            new Pais () {  Nome = "ILHAS CAIMAN",                           Sigla = "KY",            Ddi = "+1",                 Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "ILHAS COOK",                             Sigla = "CK",            Ddi = "+682",               Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHAS FAROE",                            Sigla = "FO",            Ddi = "+298",               Continente = "EUROPA" },
            new Pais () {  Nome = "ILHAS FALKLAND(MALVINAS)",               Sigla = "FK",            Ddi = "+500",               Continente = "AMERICA DO SUL" },
            new Pais () {  Nome = "ILHAS TURKS E CAICOS",                   Sigla = "TC",            Ddi = "+1",                 Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "ILHAS VIRGENS",                          Sigla = "VG",            Ddi = "+1",                Continente = "AMERICA CENTRAL" },
            new Pais () {  Nome = "ILHAS MARIANA DO NORTE",                 Sigla = "MP",            Ddi = "+1",                Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHAS SALOMÃO",                          Sigla = "SB",            Ddi = "+677",              Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHA CHRISTMAS",                         Sigla = "CX",            Ddi = "+672",              Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHAS COCOS",                            Sigla = "CC",            Ddi = "+672",              Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHA HEARD E ILHAS MCDONALD",            Sigla = "HM",            Ddi = "+672",              Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHAS MARSHALL",                         Sigla = "MH",            Ddi = "+692",              Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHAS NORFOLK",                          Sigla = "NF",            Ddi = "+672",              Continente = "OCEANIA" },
            new Pais () {  Nome = "ILHAS SEICHELES",                        Sigla = "SC",            Ddi="+248",                Continente = "ÁFRICA" },
            new Pais () {  Nome = "ÍNDIA",                                  Sigla = "IN",            Ddi= "+91",                Continente = "ASIA" },
            new Pais () {  Nome = "INGLATERRA",                             Sigla = "GB",            Ddi= "+44",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "INDONÉSIA",                             Sigla = "ID",            Ddi= "+62",                Continente = "ASIA" },
            new Pais ()  {  Nome = "IRÃ",                                   Sigla = "IR",            Ddi= "+98",                Continente = "ASIA" },
            new Pais ()  {  Nome = "IRAQUE",                                Sigla = "IQ",            Ddi= "+964",               Continente = "ASIA" },
            new Pais ()  {  Nome = "IRLANDA",                               Sigla = "IE",            Ddi= "+353",               Continente = "EUROPA" },
            new Pais ()  {  Nome = "ISLÂNDIA",                              Sigla = "IS",            Ddi= "+354",               Continente = "EUROPA" },
            new Pais ()  {  Nome = "ISRAEL",                                Sigla = "IL",            Ddi= "+972",               Continente = "ASIA" },
            new Pais ()  {  Nome = "ITÁLIA",                                Sigla = "IT",            Ddi= "+39",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "JAMAICA",                               Sigla = "JM",            Ddi= "+1",                 Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "JAPÃO",                                 Sigla = "JP",           Ddi= "+81",                 Continente = "ASIA" },
            new Pais ()  {  Nome = "JERSEY",                                Sigla = "JE",           Ddi= "+44",                 Continente = "EUROPA" },
            new Pais ()  {  Nome = "JORDÂNIA",                              Sigla = "JO",           Ddi= "+962",                Continente = "ASIA" },
            new Pais ()  {  Nome = "KIRIBATI",                              Sigla = "KI",           Ddi= "+686",                Continente = "OCEANIA" },
            new Pais ()  {  Nome = "KOSOVO",                                Sigla = "XK",           Ddi= "+383",                Continente = "Europa" },
            new Pais ()  {  Nome = "KUWAIT",                                Sigla = "KW",           Ddi= " +965",               Continente = "ASIA" },
            new Pais ()  {  Nome = "LAOS",                                  Sigla = "LA",           Ddi= "+856",                Continente = "ASIA" },
            new Pais ()  {  Nome = "LESOTO",                                Sigla = "LS",           Ddi= "+266",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "LETÔNIA",                               Sigla = "LV",           Ddi= "+371",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "LÍBANO",                                Sigla = "LB",           Ddi= "+961",                Continente = "ASIA" },
            new Pais ()  {  Nome = "LIBÉRIA",                               Sigla = "LR",           Ddi= "+231",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "LÍBIA",                                 Sigla = "LY",           Ddi= "+218",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "LIECHTENSTEIN",                         Sigla = "LI",           Ddi= "+423",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "LITUÂNIA",                              Sigla = "LT",           Ddi= "+370",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "LUXEMBURGO",                            Sigla = "LU",           Ddi= "+352 ",               Continente = "EUROPA" },
            new Pais ()  {  Nome = "MACAU",                                 Sigla = "MO",           Ddi= "+853",                Continente = "ASIA" },
            new Pais ()  {  Nome = "MACEDÔNIA",                             Sigla = "MK",           Ddi = "+389",               Continente = "EUROPA" },
            new Pais ()  {  Nome = "MADAGASCAR",                            Sigla = "MG",           Ddi= "+261",                Continente = "AFRICA" },
            new Pais ()  { Nome =  "MAIOTE",                                Sigla = "YT",           Ddi = "+269",               Continente = "AFRICA" },
            new Pais ()  {  Nome = "MALÁSIA",                               Sigla = "MY",           Ddi= "+60",                 Continente = "ASIA" },
            new Pais ()  {  Nome = "MALAWI",                                Sigla = "MW",           Ddi= "+265",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "MALDIVAS",                              Sigla = "MV",           Ddi= "+960",                Continente = "ASIA" },
            new Pais ()  {  Nome = "MALI",                                  Sigla = "ML",           Ddi= "+223",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "MALTA",                                 Sigla = "MT",           Ddi= "+356",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "MARROCOS",                              Sigla = "MA",           Ddi= "+212",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "MARTINICA",                             Sigla = "MQ",           Ddi = "+596",               Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "MAURÍCIO",                              Sigla = "MU",           Ddi= "+230",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "MAURITÂNIA",                            Sigla = "MR",           Ddi= "+222",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "MÉXICO",                                Sigla = "MX",           Ddi= "+52",                 Continente = "AMERICA DO NORTE" },
            new Pais ()  { Nome =  "MICRONÉSIA",                            Sigla = "FM",           Ddi = "+691",               Continente = "OCEANIA" },
            new Pais ()  {  Nome = "MIANMAR",                               Sigla = "MM",           Ddi = "+95",                Continente = "ASIA" },
            new Pais ()  {  Nome = "MOÇAMBIQUE",                            Sigla = "MZ",           Ddi = "+258",               Continente = "AFRICA" },
            new Pais ()  {  Nome = "MÔNACO",                                Sigla = "MC",           Ddi = "+377",               Continente = "EUROPA" },
            new Pais ()  {  Nome = "MONGÓLIA",                              Sigla = "MN",           Ddi = "+976",               Continente = "ASIA" },
            new Pais ()  {  Nome = "MONT SERRAT",                           Sigla = "MS",           Ddi = "+1",                 Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "MONTENEGRO",                            Sigla = "ME",           Ddi = "+382",               Continente = "EUROPA" },
            new Pais ()  {  Nome = "NAMÍBIA",                               Sigla = "NA",           Ddi = "+264",               Continente = "AFRICA" },
            new Pais ()  {  Nome = "NAURU",                                 Sigla = "NR",           Ddi = "+674",               Continente = "OCEANIA" },
            new Pais ()  {  Nome = "NEPAL",                                 Sigla = "NP",           Ddi = "+977",               Continente = "ASIA" },
            new Pais ()  {  Nome = "NICARÁGUA",                             Sigla = "NI",           Ddi = "+505",               Continente = "AMERICA CENTRAL" },
            new Pais ()  { Nome =  "NIUE",                                  Sigla = "NU",           Ddi = "+683",               Continente = "OCEANIA" },
            new Pais ()  {  Nome = "NÍGER",                                 Sigla = "NE",           Ddi = "+227",               Continente = "AFRICA" },
            new Pais ()  {  Nome = "NIGÉRIA",                               Sigla = "NG",           Ddi = "+234",               Continente = "AFRICA" },
            new Pais ()  {  Nome = "NORUEGA",                               Sigla = "NO",           Ddi = "+47",                Continente = "EUROPA" },
            new Pais ()  { Nome =  "NOVA CALEDÔNIA ",                       Sigla = "NC",           Ddi = "+687",               Continente = "OCEANIA" },
            new Pais ()  {  Nome = "NOVA ZELÂNDIA",                         Sigla = "NZ",           Ddi = "+64",                Continente = "OCEANIA" },
            new Pais ()  {  Nome = "OMÃ",                                   Sigla = "OM",           Ddi = "+968",               Continente = "ASIA" },
            new Pais ()  {  Nome = "PAÍSES BAIXOS",                         Sigla = "NL",           Ddi = "+31",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "PALAU",                                 Sigla = "PW",           Ddi = "+680",               Continente = "OCEANIA" },
            new Pais ()  {  Nome = "PALESTINA",                             Sigla = "PS",           Ddi = "+970",               Continente = "ASIA" },
            new Pais ()  {  Nome = "PANAMÁ",                                Sigla = "PA",           Ddi= "+507",                Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "PAPUA E NOVA GUINÉ",                    Sigla = "PG",           Ddi= "+675",                Continente = "OCEANIA" },
            new Pais ()  {  Nome = "PAQUISTÃO",                             Sigla = "PK",           Ddi= "+92",                 Continente = "ASIA" },
            new Pais ()  {  Nome = "PARAGUAI",                              Sigla = "PY",           Ddi= "+595",                Continente = "AMERICA DO SUL" },
            new Pais ()  {  Nome = "PERU",                                  Sigla = "PE",           Ddi= "+51",                 Continente = "AMERICA DO SUL" },
            new Pais ()  {  Nome = "POLINÉSIA FRANCESA",                    Sigla = "PF",           Ddi= "+689",                Continente = "OCEANIA" },
            new Pais ()  {  Nome = "POLÔNIA",                               Sigla = "PL",           Ddi= "+48",                 Continente = "EUROPA" },
            new Pais ()  {  Nome = "PORTUGAL",                              Sigla = "PT",           Ddi= "+351",                Continente = "EUROPA" },
            new Pais ()  {  Nome =  "PORTO RICO",                           Sigla = "PR",           Ddi = "+1",                 Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "QUÊNIA",                                Sigla = "KE",           Ddi= "+254",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "QUIRGUISTÃO",                           Sigla = "KG",           Ddi= "+996",                Continente = "ASIA" },
            new Pais ()  {  Nome = "REPÚBLICA CENTRO AFRICANA",             Sigla = "CF",           Ddi= "+236",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "MOLDAVIA",                              Sigla = "MD",           Ddi= "+373",                Continente = "europa" },
            new Pais ()  {  Nome = "REPÚBLICA DOMINICANA",                  Sigla = "DO",           Ddi= "+1",                  Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "REPÚBLICA TCHECA",                      Sigla = "CZ",           Ddi= "+420",                Continente = "EUROPA" },
            new Pais ()  {  Nome =  "REUNIÃO",                              Sigla = "RE",           Ddi = "+262",               Continente = "AFRICA" },
            new Pais ()  {  Nome = "ROMÊNIA",                               Sigla = "RO",           Ddi= "+40",                 Continente = "EUROPA" },
            new Pais ()  {  Nome = "RUANDA",                                Sigla = "RW",           Ddi= "+250",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "RUSSIA",                                Sigla = "RU",           Ddi= "+7",                  Continente = "ASIA" },
            new Pais ()  {  Nome = "SAARA OCIDENTAL",                       Sigla = "EH",           Ddi= "+212",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SAMOA",                                 Sigla = "WS",           Ddi= "+685",                Continente = "OCEANIA" },
            new Pais ()  {  Nome = "SAMOA AMERICANA",                       Sigla = "AS",           Ddi = "+1",                 Continente = "OCEANIA" }, 
            new Pais ()  {  Nome = "SANTA HELENA",                          Sigla = "SH",           Ddi= "+290",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SANTA LÚCIA",                           Sigla = "LC",           Ddi= "+1",                  Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "SÃO CRISTÓVÃO E NEVIS",                 Sigla = "KN",           Ddi= "+1",                  Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "SÃO MARINO",                            Sigla =  "SM",          Ddi= "+378",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "SÃO PEDRO E MIQUELÃO",                  Sigla =  "PM",          Ddi= "+508",                Continente = "AMERICA DO NORTE" }, 
            new Pais ()  {  Nome = "SÃO TOMÉ E PRÍNCIPE",                   Sigla = "ST",           Ddi= "+239",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SÃO VICENTE E GRANADINAS",              Sigla = "VC",           Ddi= "+1",                  Continente = "AMERICA CENTRAL" },
            new Pais ()  {  Nome = "SENEGAL",                               Sigla = "SN",           Ddi= "+221",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SERRA LEOA",                            Sigla = "SL",           Ddi= "+232",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SÉRVIA",                                Sigla = "RS",           Ddi= "+381",                Continente = "EUROPA" },
            new Pais ()  {  Nome = "SINGAPURA",                             Sigla = "SG",           Ddi= "+65",                 Continente = "ASIA" },
            new Pais ()  {  Nome = "SÍRIA",                                 Sigla = "SY",           Ddi= "+963",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SOMÁLIA",                               Sigla = "SO",           Ddi= "+252",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SRI LANKA",                             Sigla = "LK",           Ddi= "+94",                 Continente = "ASIA" },
            new Pais ()  {  Nome = "SUAZILÂNDIA",                           Sigla = "SZ",           Ddi= "+268",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SUDÃO",                                 Sigla = "SD",           Ddi= "+249",                Continente = "AFRICA" },
            new Pais ()  {  Nome = "SUDÃO DO SUL",                          Sigla = "SS",           Ddi= "+211",                Continente = "AFRICA" }, 
            new Pais ()  { Nome =   "SUÉCIA",                               Sigla = "SE",           Ddi= "+46",                 Continente = "EUROPA" },
            new Pais ()  { Nome =  "SUÍÇA",                                 Sigla = "CH",           Ddi= "+41",                 Continente = "EUROPA" },
            new Pais ()  { Nome =  "SURINAME",                              Sigla = "SR",           Ddi= "+597",                Continente = "AMERICA DO SUL" },
            new Pais ()  { Nome =  "SVALBARD E JAN MAYEN",                  Sigla = "SJ",           Ddi= "+47",                 Continente = "EUROPA" },
            new Pais ()  { Nome =  "TADJIQUISTÃO",                          Sigla = "TJ",           Ddi= "+992",                Continente = "ASIA" },
            new Pais ()  { Nome =  "TAILÂNDIA",                             Sigla = "TH",           Ddi= "+66 ",                Continente = "ASIA" },
            new Pais ()  { Nome =  "TAIWAN",                                Sigla = "TW",           Ddi= "+886",                Continente = "ASIA" },
            new Pais ()  { Nome =  "TANZÂNIA",                              Sigla = "TZ",           Ddi= "+255",                Continente = "AFRICA" },
            new Pais ()  { Nome =  "TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO", Sigla = "IO",           Ddi = "+246",               Continente = "AFRICA" },
            new Pais ()  { Nome =  "TIMOR LESTE",                           Sigla = "TP",           Ddi= "+670 ",               Continente = "ASIA" },
            new Pais ()  { Nome =  "TOGO",                                  Sigla = "TG",           Ddi= "+228",                Continente = "AFRICA" },
            new Pais ()  { Nome =  "TONGA",                                 Sigla = "TO",           Ddi= "+676",                Continente = "OCEANIA" },
            new Pais ()  { Nome =  "TOQUELAU",                              Sigla = "TK",           Ddi = "+690",               Continente = "OCEANIA" },
            new Pais ()  { Nome =  "TRINDAD E TOBAGO",                      Sigla = "TT",           Ddi= "+1",                  Continente = "AMERICA CENTRAL" },
            new Pais ()  { Nome =  "TUNÍSIA",                               Sigla = "TN",           Ddi= "+216",                Continente = "AFRICA" },
             new Pais ()  { Nome =  "TURCOMENISTÃO",                        Sigla = "TM",           Ddi= "+993",                Continente = "ASIA" },
             new Pais ()  { Nome =  "TURQUIA",                              Sigla = "TR",           Ddi= "+90",                 Continente = "ASIA/EUROPA" },
             new Pais ()  { Nome =  "TUVALU",                               Sigla = "TV",           Ddi= "+688",                Continente = "OCEANIA" },
             new Pais ()  { Nome =  "UCRÂNIA",                              Sigla = "UA",           Ddi= "+380",                Continente = "EUROPA" },
             new Pais ()  { Nome =  "UGANDA",                               Sigla = "UG",           Ddi= "+256",                Continente = "AFRICA" },
             new Pais ()  { Nome =  "URUGUAI",                              Sigla = "UY",           Ddi= "+598",                Continente = "AMERICA DO SUL" },
             new Pais ()  { Nome =  "UZBEQUISTÃO",                          Sigla = "UZ",           Ddi= "+998",                Continente = "ASIA" },
             new Pais ()  { Nome =  "VANUATU",                              Sigla = "VU",           Ddi= "+678",                Continente = "OCEANIA" },
             new Pais ()  { Nome =  "VATICANO",                             Sigla = "VA",           Ddi= "+379",                Continente = "EUROPA" },
             new Pais ()  { Nome =  "VENEZUELA",                            Sigla = "VE",           Ddi= "+58",                 Continente = "AMERICA DO SUL" },
             new Pais ()  { Nome =  "VIETNÃ",                               Sigla = "VN",           Ddi= "+84",                 Continente = "ASIA" },
             new Pais ()  { Nome =  "WALLIS E FUTUNA",                      Sigla = "WF",           Ddi = "+681",               Continente = "OCEANIA" },
             new Pais ()  { Nome =  "ZÂMBIA",                               Sigla = "ZM",           Ddi= "+260",                Continente = "AFRICA" },
             new Pais ()  { Nome =  "ZIMBÁBWE",                             Sigla = "ZW",           Ddi= "+263",                Continente = "AFRICA" },
    };
}
