using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Drawing;
using System.Runtime.InteropServices;
using System.Text;

namespace CastelloBranco.Singletons;

public static class WorldCountries
{
    public static List<Country> Countries = new List<Country>()
    {
            new Country () { Name = "AFEGANISTÃO",                              Acronym = "AF",           CountryCode = "+93",             Continent = "ASIA" },
            new Country () { Name = "ÁFRICA DO SUL",                            Acronym = "ZA",           CountryCode ="+27",              Continent = "AFRICA" },
            new Country () { Name = "ALBÂNIA",                                  Acronym = "AL",           CountryCode = "+355",            Continent = "EUROPA" },
            new Country () { Name = "ALEMANHA",                                 Acronym = "DE",           CountryCode = "+49",             Continent = "EUROPA" },
            new Country () { Name = "ANDORRA",                                  Acronym = "AD",           CountryCode = "+376",            Continent = "EUROPA" },
            new Country () { Name = "ANGOLA",                                   Acronym = "AO",           CountryCode = "+244",            Continent = "AFRICA" },
            new Country () { Name = "ANGUILLA",                                 Acronym = "AI",           CountryCode = "+1",              Continent = "AMERICA CENTRAL" },
            new Country () { Name = "REPÚBLICA DA MACEDÔNIA",                   Acronym = "MK",           CountryCode = "+389",            Continent = "EUROPA" },
            new Country () { Name = "ANTÍGUA E BARBUDA",                        Acronym = "AG",           CountryCode = "+1",              Continent = "AMERICA CENTRAL" },
            new Country () { Name = "ANTILHAS HOLANDESAS",                      Acronym = "AN",           CountryCode = "+599",            Continent = "AMERICA CENTRAL" },
            new Country () { Name = "ARÁBIA SAUDITA",                           Acronym = "SA",           CountryCode = "+966",            Continent = "ASIA" },
            new Country () { Name = "ARGÉLIA",                                  Acronym = "DZ",           CountryCode = "+213",            Continent = "AFRICA" },
            new Country () { Name = "ARGENTINA",                                Acronym = "AR",           CountryCode = "+54",             Continent = "AMERICA DO SUL" },
            new Country () { Name = "ARMÊNIA",                                  Acronym = "AM",           CountryCode = "+374",            Continent = "ASIA" },
            new Country () { Name = "ARUBA",                                    Acronym = "AW",           CountryCode = "+297",            Continent = "AMERICA DO SUL" },
            new Country () { Name = "ASCENSAO",                                 Acronym = "SH",           CountryCode = "+247",            Continent = "AFRICA" },
            new Country () { Name = "AUSTRÁLIA",                                Acronym = "AU",           CountryCode = "+61",             Continent = "OCEANIA" },
            new Country () { Name = "ÁUSTRIA",                                  Acronym = "AT",           CountryCode = "+43",             Continent = "EUROPA" },
            new Country () { Name = "ARZEBAIDJÃO",                              Acronym = "AZ",           CountryCode = "+994",            Continent = "ASIA" },
            new Country () { Name = "BAHAMAS",                                  Acronym = "BS",           CountryCode = "+1",               Continent = "AMERICA CENTRAL" },
            new Country () { Name = "BANGLADESH",                               Acronym = "BD",           CountryCode = "+880",             Continent = "ASIA" },
            new Country () { Name = "BARBADOS",                                 Acronym = "BB",           CountryCode = "+1",               Continent = "AMERICA CENTRAL" },
            new Country () { Name = "BAREINE",                                  Acronym = "BH",           CountryCode = "+973",             Continent = "ASIA" },
            new Country () { Name = "BELARUS",                                  Acronym = "BY",           CountryCode = "+375",             Continent = "EUROPA" },
            new Country () { Name = "BÉLGICA",                                  Acronym = "BE",           CountryCode = "+32",              Continent = "EUROPA" },
            new Country () { Name = "BELIZE",                                   Acronym = "BZ",           CountryCode = "+501",             Continent = "AMERICA CENTRAL" },
            new Country () { Name = "BENIN",                                    Acronym = "BJ",           CountryCode = "+229",             Continent = "AFRICA" },
            new Country () { Name = "BERMUDAS",                                 Acronym = "BM",           CountryCode = "+1",               Continent = "AMERICA CENTRAL" },
            new Country () { Name = "BOLÍVIA",                                  Acronym = "BO",           CountryCode = "+591",             Continent = "AMERICA DO SUL" },
            new Country () { Name = "BÓSNIA E HERZEGÓVINA",                     Acronym = "BA",           CountryCode = "+387",             Continent = "EUROPA" },
            new Country () { Name = "BOTSWANA",                                 Acronym = "BW",           CountryCode = "+267",             Continent = "AFRICA" },
            new Country () { Name = "BRASIL",                                   Acronym = "BR",           CountryCode = "+55",              Continent = "AMERICA DO SUL" },
            new Country () { Name = "BRUNEI DARUSSALAM",                        Acronym = "BN",           CountryCode = "+673",             Continent = "ASIA" },
            new Country () { Name = "BULGÁRIA",                                 Acronym = "BG",           CountryCode = "+359",             Continent = "EUROPA" },
            new Country () { Name = "BURKINA FASO",                             Acronym = "BF",           CountryCode = "+226",             Continent = "AFRICA" },
            new Country () { Name = "BURUNDI",                                  Acronym = "BI",           CountryCode = "+257",             Continent = "AFRICA" },
            new Country () { Name = "BUTÃO",                                    Acronym = "BT",           CountryCode = "+975",             Continent = "ASIA" },
            new Country () { Name = "CABO VERDE",                               Acronym = "CV",           CountryCode = "+238",             Continent = "AFRICA" },
            new Country () { Name = "CAMARÕES",                                 Acronym = "CM",           CountryCode = "+237",             Continent = "AFRICA" },
            new Country () { Name = "CAMBOJA",                                  Acronym = "KH",           CountryCode = "+855",             Continent = "ASIA" },
            new Country () { Name =  "CANADÁ",                                  Acronym = "CA",           CountryCode = "+1",               Continent = "AMERICA DO NORTE" },
            new Country () { Name =  "CATAR",                                   Acronym = "QA",           CountryCode = "+974",             Continent = "ASIA" },
            new Country () { Name =  "CAZAQUISTÃO",                             Acronym = "KZ",           CountryCode = "+7",               Continent = "ASIA" },
            new Country () { Name =  "CHADE",                                   Acronym = "TD",           CountryCode = "+237",             Continent = "AFRICA" },
            new Country () { Name =  "CHILE",                                   Acronym = "CL",           CountryCode = "+56",              Continent = "AMERICA DO SUL" },
            new Country () { Name =  "CHINA",                                   Acronym = "CN",           CountryCode = "+86",              Continent = "ASIA" },
            new Country () { Name =  "CHIPRE",                                  Acronym = "CY",           CountryCode = " +357",            Continent = "EUROPA" },
            new Country () { Name =  "COLÔMBIA",                                Acronym = "CO",           CountryCode = "+57",              Continent = "AMERICA DO SUL" },
            new Country () { Name =  "COMORES",                                 Acronym = "KM",           CountryCode = "+269",             Continent = "AFRICA" },
            new Country () { Name =  "CONGO BRAZAVILE",                         Acronym = "CG",           CountryCode = "+242",             Continent = "AFRICA" },
            new Country () { Name =  "CONGO KINSHASA",                          Acronym = "CD",           CountryCode = "+243",             Continent = "AFRICA" },
            new Country () {  Name = "COREIA DO NORTE",                         Acronym = "KP",           CountryCode = "+850",             Continent = "ASIA" },
            new Country () {  Name = "COREIA DO SUL",                           Acronym = "KR",           CountryCode = "+882",             Continent = "ASIA" },
            new Country () { Name =  "COSTA DO MARFIM",                         Acronym = "CI",           CountryCode = "+225",             Continent = "AFRICA" },
            new Country () { Name =  "COSTA RICA",                              Acronym = "CR",           CountryCode = "+506",             Continent = "AMERICA CENTRAL" },
            new Country () { Name =  "CROÁCIA",                                 Acronym = "HR",           CountryCode = "+385",             Continent = "EUROPA" },
            new Country () { Name =  "CUBA",                                    Acronym = "CU",           CountryCode = "+53",              Continent = "AMERICA CENTRAL" },
            new Country () { Name =  "DINAMARCA",                               Acronym = "DK",           CountryCode = "+45",              Continent = "EUROPA" },
            new Country () { Name =  "DJIBUTI",                                 Acronym = "DJ",           CountryCode = "+253",             Continent = "AFRICA" },
            new Country () { Name =  "DOMINICA",                                Acronym = "DM",           CountryCode = "+1",               Continent = "AMERICA CENTRAL" },
            new Country () { Name =  "EGITO",                                   Acronym = "EG",           CountryCode = "+20",              Continent = "AFRICA" },
            new Country () { Name =  "EL SALVADOR",                             Acronym = "SV",           CountryCode = "+503",             Continent = "AMERICA CENTRAL" },
            new Country () { Name =  "EMIRADOS ÁRABES UNIDOS",                  Acronym = "AE",           CountryCode = "+971",             Continent = "AFRICA" },
            new Country () { Name =  "EQUADOR",                                 Acronym = "EC",           CountryCode = "+593",             Continent = "AMERICA DO SUL" },
            new Country () { Name =  "ERITRÉIA",                                Acronym = "ER",           CountryCode = "+291",             Continent = "AFRICA" },
            new Country () { Name =  "ESLOVÁQUIA",                              Acronym = "SK",           CountryCode = "+421",             Continent = "EUROPA" },
            new Country () { Name =  "ESLOVÊNIA",                               Acronym = "SI",           CountryCode = "+386",             Continent = "EUROPA" },
            new Country () { Name =  "ESPANHA",                                 Acronym = "ES",           CountryCode = "+34",              Continent = "EUROPA" },
            new Country () { Name =  "ESTADOS UNIDOS DA AMÉRICA",               Acronym = "US",           CountryCode = "+1",               Continent = "AMERICA DO NORTE" },
            new Country () { Name =  "ESTÔNIA",                                 Acronym = "EE",           CountryCode = "+372",             Continent = "EUROPA" },
            new Country () {  Name = "ETIÓPIA",                                 Acronym = "ET",           CountryCode = "+251",             Continent = "AFRICA" },
            new Country () {  Name = "FIJI",                                    Acronym = "FJ",           CountryCode = "+679",             Continent = "OCEANIA" },
            new Country () {  Name = "FILIPINAS",                               Acronym = "PH",           CountryCode = "+63",              Continent = "ASIA" },
            new Country () {  Name = "FINLÂNDIA",                               Acronym="FI",             CountryCode = "+358",             Continent = "EUROPA" },
            new Country () {  Name = "FRANÇA",                                  Acronym="FR",             CountryCode = "+33",              Continent = "EUROPA" },
            new Country () {  Name = "GABÃO",                                   Acronym = "GA",           CountryCode = "+241",             Continent = "AFRICA" },
            new Country () {  Name = "GÂMBIA",                                  Acronym = "GM",           CountryCode = "+220",             Continent = "AFRICA" },
            new Country () {  Name = "GANA",                                    Acronym = "GH",           CountryCode = "+233",             Continent = "AFRICA" },
            new Country () {  Name = "GEÓRGIA",                                 Acronym = "GE",           CountryCode = "+995",             Continent = "ASIA" },
            new Country () {  Name = "GEÓRGIA DO SUL E ILHAS SANDWICH DO SUL",  Acronym = "GS",           CountryCode = "+500",             Continent = "AMERICA DO SUL" },
            new Country () {  Name = "GIBRALTAR",                               Acronym = "GI",           CountryCode = "+350",             Continent = "EUROPA" },
            new Country () {  Name = "GRANADA",                                 Acronym = "GD",           CountryCode = "+1",               Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "GRÉCIA",                                  Acronym = "GR",           CountryCode = "+30",              Continent = "EUROPA" },
            new Country () {  Name = "GROELÂNDIA",                              Acronym = "GL",           CountryCode = "+299",             Continent = "AMERICA DO NORTE" },
            new Country ()  { Name = "GUADALUPE",                               Acronym = "GP",           CountryCode = "+590",             Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "GUAM",                                    Acronym = "GU",           CountryCode = "+671",             Continent = "OCEANIA" },
            new Country () {  Name = "GUATEMALA",                               Acronym = "GT",           CountryCode = "+502",             Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "GUERNSEY",                                Acronym = "GG",           CountryCode = "+44",              Continent = "EUROPA" },
            new Country () {  Name = "GUIANA",                                  Acronym = "GY",           CountryCode = "+592",             Continent = "AMERICA DO SUL" },
            new Country () {  Name = "GUIANA FRANCESA",                         Acronym = "GF",           CountryCode = "+594",             Continent = "AMERICA DO SUL" },
            new Country () {  Name = "GUINÉ",                                  Acronym = "GN",            CountryCode = "+224",             Continent = "AFRICA" },
            new Country () {  Name = "GUINÉ BISSAU",                           Acronym = "GW",            CountryCode = "+245",             Continent = "AFRICA" },
            new Country () {  Name = "GUINÉ EQUATORIAL",                       Acronym = "GQ",            CountryCode = "+240",             Continent = "AFRICA" },
            new Country () {  Name =  "HAITI",                                 Acronym = "HT",            CountryCode = "+509",             Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "HOLANDA",                                Acronym = "NL",            CountryCode = "+31",              Continent = "EUROPA" },
            new Country () {  Name = "HONDURAS",                               Acronym = "HN",            CountryCode = "+504",               Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "HONG-KONG",                              Acronym = "HK",            CountryCode = "+852",               Continent = "ASIA" },
            new Country () {  Name = "HUNGRIA",                                Acronym = "HU",            CountryCode = "+36",                Continent = "EUROPA" },
            new Country () {  Name = "IÊMEN",                                  Acronym = "YE",            CountryCode = "+967",               Continent = "IEMEN" },
            new Country () {  Name = "ILHA BOUVET",                            Acronym = "BV",            CountryCode = "+47",                Continent = "ANTARTIDA" },
            new Country () {  Name = "ILHAS CAIMAN",                           Acronym = "KY",            CountryCode = "+1",                 Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "ILHAS COOK",                             Acronym = "CK",            CountryCode = "+682",               Continent = "OCEANIA" },
            new Country () {  Name = "ILHAS FAROE",                            Acronym = "FO",            CountryCode = "+298",               Continent = "EUROPA" },
            new Country () {  Name = "ILHAS FALKLAND(MALVINAS)",               Acronym = "FK",            CountryCode = "+500",               Continent = "AMERICA DO SUL" },
            new Country () {  Name = "ILHAS TURKS E CAICOS",                   Acronym = "TC",            CountryCode = "+1",                 Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "ILHAS VIRGENS",                          Acronym = "VG",            CountryCode = "+1",                Continent = "AMERICA CENTRAL" },
            new Country () {  Name = "ILHAS MARIANA DO NORTE",                 Acronym = "MP",            CountryCode = "+1",                Continent = "OCEANIA" },
            new Country () {  Name = "ILHAS SALOMÃO",                          Acronym = "SB",            CountryCode = "+677",              Continent = "OCEANIA" },
            new Country () {  Name = "ILHA CHRISTMAS",                         Acronym = "CX",            CountryCode = "+672",              Continent = "OCEANIA" },
            new Country () {  Name = "ILHAS COCOS",                            Acronym = "CC",            CountryCode = "+672",              Continent = "OCEANIA" },
            new Country () {  Name = "ILHA HEARD E ILHAS MCDONALD",            Acronym = "HM",            CountryCode = "+672",              Continent = "OCEANIA" },
            new Country () {  Name = "ILHAS MARSHALL",                         Acronym = "MH",            CountryCode = "+692",              Continent = "OCEANIA" },
            new Country () {  Name = "ILHAS NORFOLK",                          Acronym = "NF",            CountryCode = "+672",              Continent = "OCEANIA" },
            new Country () {  Name = "ILHAS SEICHELES",                        Acronym = "SC",            CountryCode="+248",                Continent = "ÁFRICA" },
            new Country () {  Name = "ÍNDIA",                                  Acronym = "IN",            CountryCode= "+91",                Continent = "ASIA" },
            new Country () {  Name = "INGLATERRA",                             Acronym = "GB",            CountryCode= "+44",                Continent = "EUROPA" },
            new Country ()  {  Name = "INDONÉSIA",                             Acronym = "ID",            CountryCode= "+62",                Continent = "ASIA" },
            new Country ()  {  Name = "IRÃ",                                   Acronym = "IR",            CountryCode= "+98",                Continent = "ASIA" },
            new Country ()  {  Name = "IRAQUE",                                Acronym = "IQ",            CountryCode= "+964",               Continent = "ASIA" },
            new Country ()  {  Name = "IRLANDA",                               Acronym = "IE",            CountryCode= "+353",               Continent = "EUROPA" },
            new Country ()  {  Name = "ISLÂNDIA",                              Acronym = "IS",            CountryCode= "+354",               Continent = "EUROPA" },
            new Country ()  {  Name = "ISRAEL",                                Acronym = "IL",            CountryCode= "+972",               Continent = "ASIA" },
            new Country ()  {  Name = "ITÁLIA",                                Acronym = "IT",            CountryCode= "+39",                Continent = "EUROPA" },
            new Country ()  {  Name = "JAMAICA",                               Acronym = "JM",            CountryCode= "+1",                 Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "JAPÃO",                                 Acronym = "JP",           CountryCode= "+81",                 Continent = "ASIA" },
            new Country ()  {  Name = "JERSEY",                                Acronym = "JE",           CountryCode= "+44",                 Continent = "EUROPA" },
            new Country ()  {  Name = "JORDÂNIA",                              Acronym = "JO",           CountryCode= "+962",                Continent = "ASIA" },
            new Country ()  {  Name = "KIRIBATI",                              Acronym = "KI",           CountryCode= "+686",                Continent = "OCEANIA" },
            new Country ()  {  Name = "KOSOVO",                                Acronym = "XK",           CountryCode= "+383",                Continent = "Europa" },
            new Country ()  {  Name = "KUWAIT",                                Acronym = "KW",           CountryCode= " +965",               Continent = "ASIA" },
            new Country ()  {  Name = "LAOS",                                  Acronym = "LA",           CountryCode= "+856",                Continent = "ASIA" },
            new Country ()  {  Name = "LESOTO",                                Acronym = "LS",           CountryCode= "+266",                Continent = "AFRICA" },
            new Country ()  {  Name = "LETÔNIA",                               Acronym = "LV",           CountryCode= "+371",                Continent = "EUROPA" },
            new Country ()  {  Name = "LÍBANO",                                Acronym = "LB",           CountryCode= "+961",                Continent = "ASIA" },
            new Country ()  {  Name = "LIBÉRIA",                               Acronym = "LR",           CountryCode= "+231",                Continent = "AFRICA" },
            new Country ()  {  Name = "LÍBIA",                                 Acronym = "LY",           CountryCode= "+218",                Continent = "AFRICA" },
            new Country ()  {  Name = "LIECHTENSTEIN",                         Acronym = "LI",           CountryCode= "+423",                Continent = "EUROPA" },
            new Country ()  {  Name = "LITUÂNIA",                              Acronym = "LT",           CountryCode= "+370",                Continent = "EUROPA" },
            new Country ()  {  Name = "LUXEMBURGO",                            Acronym = "LU",           CountryCode= "+352 ",               Continent = "EUROPA" },
            new Country ()  {  Name = "MACAU",                                 Acronym = "MO",           CountryCode= "+853",                Continent = "ASIA" },
            new Country ()  {  Name = "MACEDÔNIA",                             Acronym = "MK",           CountryCode = "+389",               Continent = "EUROPA" },
            new Country ()  {  Name = "MADAGASCAR",                            Acronym = "MG",           CountryCode= "+261",                Continent = "AFRICA" },
            new Country ()  { Name =  "MAIOTE",                                Acronym = "YT",           CountryCode = "+269",               Continent = "AFRICA" },
            new Country ()  {  Name = "MALÁSIA",                               Acronym = "MY",           CountryCode= "+60",                 Continent = "ASIA" },
            new Country ()  {  Name = "MALAWI",                                Acronym = "MW",           CountryCode= "+265",                Continent = "AFRICA" },
            new Country ()  {  Name = "MALDIVAS",                              Acronym = "MV",           CountryCode= "+960",                Continent = "ASIA" },
            new Country ()  {  Name = "MALI",                                  Acronym = "ML",           CountryCode= "+223",                Continent = "AFRICA" },
            new Country ()  {  Name = "MALTA",                                 Acronym = "MT",           CountryCode= "+356",                Continent = "EUROPA" },
            new Country ()  {  Name = "MARROCOS",                              Acronym = "MA",           CountryCode= "+212",                Continent = "AFRICA" },
            new Country ()  {  Name = "MARTINICA",                             Acronym = "MQ",           CountryCode = "+596",               Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "MAURÍCIO",                              Acronym = "MU",           CountryCode= "+230",                Continent = "AFRICA" },
            new Country ()  {  Name = "MAURITÂNIA",                            Acronym = "MR",           CountryCode= "+222",                Continent = "AFRICA" },
            new Country ()  {  Name = "MÉXICO",                                Acronym = "MX",           CountryCode= "+52",                 Continent = "AMERICA DO NORTE" },
            new Country ()  { Name =  "MICRONÉSIA",                            Acronym = "FM",           CountryCode = "+691",               Continent = "OCEANIA" },
            new Country ()  {  Name = "MIANMAR",                               Acronym = "MM",           CountryCode = "+95",                Continent = "ASIA" },
            new Country ()  {  Name = "MOÇAMBIQUE",                            Acronym = "MZ",           CountryCode = "+258",               Continent = "AFRICA" },
            new Country ()  {  Name = "MÔNACO",                                Acronym = "MC",           CountryCode = "+377",               Continent = "EUROPA" },
            new Country ()  {  Name = "MONGÓLIA",                              Acronym = "MN",           CountryCode = "+976",               Continent = "ASIA" },
            new Country ()  {  Name = "MONT SERRAT",                           Acronym = "MS",           CountryCode = "+1",                 Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "MONTENEGRO",                            Acronym = "ME",           CountryCode = "+382",               Continent = "EUROPA" },
            new Country ()  {  Name = "NAMÍBIA",                               Acronym = "NA",           CountryCode = "+264",               Continent = "AFRICA" },
            new Country ()  {  Name = "NAURU",                                 Acronym = "NR",           CountryCode = "+674",               Continent = "OCEANIA" },
            new Country ()  {  Name = "NEPAL",                                 Acronym = "NP",           CountryCode = "+977",               Continent = "ASIA" },
            new Country ()  {  Name = "NICARÁGUA",                             Acronym = "NI",           CountryCode = "+505",               Continent = "AMERICA CENTRAL" },
            new Country ()  { Name =  "NIUE",                                  Acronym = "NU",           CountryCode = "+683",               Continent = "OCEANIA" },
            new Country ()  {  Name = "NÍGER",                                 Acronym = "NE",           CountryCode = "+227",               Continent = "AFRICA" },
            new Country ()  {  Name = "NIGÉRIA",                               Acronym = "NG",           CountryCode = "+234",               Continent = "AFRICA" },
            new Country ()  {  Name = "NORUEGA",                               Acronym = "NO",           CountryCode = "+47",                Continent = "EUROPA" },
            new Country ()  { Name =  "NOVA CALEDÔNIA ",                       Acronym = "NC",           CountryCode = "+687",               Continent = "OCEANIA" },
            new Country ()  {  Name = "NOVA ZELÂNDIA",                         Acronym = "NZ",           CountryCode = "+64",                Continent = "OCEANIA" },
            new Country ()  {  Name = "OMÃ",                                   Acronym = "OM",           CountryCode = "+968",               Continent = "ASIA" },
            new Country ()  {  Name = "PAÍSES BAIXOS",                         Acronym = "NL",           CountryCode = "+31",                Continent = "EUROPA" },
            new Country ()  {  Name = "PALAU",                                 Acronym = "PW",           CountryCode = "+680",               Continent = "OCEANIA" },
            new Country ()  {  Name = "PALESTINA",                             Acronym = "PS",           CountryCode = "+970",               Continent = "ASIA" },
            new Country ()  {  Name = "PANAMÁ",                                Acronym = "PA",           CountryCode= "+507",                Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "PAPUA E NOVA GUINÉ",                    Acronym = "PG",           CountryCode= "+675",                Continent = "OCEANIA" },
            new Country ()  {  Name = "PAQUISTÃO",                             Acronym = "PK",           CountryCode= "+92",                 Continent = "ASIA" },
            new Country ()  {  Name = "PARAGUAI",                              Acronym = "PY",           CountryCode= "+595",                Continent = "AMERICA DO SUL" },
            new Country ()  {  Name = "PERU",                                  Acronym = "PE",           CountryCode= "+51",                 Continent = "AMERICA DO SUL" },
            new Country ()  {  Name = "POLINÉSIA FRANCESA",                    Acronym = "PF",           CountryCode= "+689",                Continent = "OCEANIA" },
            new Country ()  {  Name = "POLÔNIA",                               Acronym = "PL",           CountryCode= "+48",                 Continent = "EUROPA" },
            new Country ()  {  Name = "PORTUGAL",                              Acronym = "PT",           CountryCode= "+351",                Continent = "EUROPA" },
            new Country ()  {  Name =  "PORTO RICO",                           Acronym = "PR",           CountryCode = "+1",                 Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "QUÊNIA",                                Acronym = "KE",           CountryCode= "+254",                Continent = "AFRICA" },
            new Country ()  {  Name = "QUIRGUISTÃO",                           Acronym = "KG",           CountryCode= "+996",                Continent = "ASIA" },
            new Country ()  {  Name = "REPÚBLICA CENTRO AFRICANA",             Acronym = "CF",           CountryCode= "+236",                Continent = "AFRICA" },
            new Country ()  {  Name = "MOLDAVIA",                              Acronym = "MD",           CountryCode= "+373",                Continent = "europa" },
            new Country ()  {  Name = "REPÚBLICA DOMINICANA",                  Acronym = "DO",           CountryCode= "+1",                  Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "REPÚBLICA TCHECA",                      Acronym = "CZ",           CountryCode= "+420",                Continent = "EUROPA" },
            new Country ()  {  Name =  "REUNIÃO",                              Acronym = "RE",           CountryCode = "+262",               Continent = "AFRICA" },
            new Country ()  {  Name = "ROMÊNIA",                               Acronym = "RO",           CountryCode= "+40",                 Continent = "EUROPA" },
            new Country ()  {  Name = "RUANDA",                                Acronym = "RW",           CountryCode= "+250",                Continent = "AFRICA" },
            new Country ()  {  Name = "RUSSIA",                                Acronym = "RU",           CountryCode= "+7",                  Continent = "ASIA" },
            new Country ()  {  Name = "SAARA OCIDENTAL",                       Acronym = "EH",           CountryCode= "+212",                Continent = "AFRICA" },
            new Country ()  {  Name = "SAMOA",                                 Acronym = "WS",           CountryCode= "+685",                Continent = "OCEANIA" },
            new Country ()  {  Name = "SAMOA AMERICANA",                       Acronym = "AS",           CountryCode = "+1",                 Continent = "OCEANIA" }, 
            new Country ()  {  Name = "SANTA HELENA",                          Acronym = "SH",           CountryCode= "+290",                Continent = "AFRICA" },
            new Country ()  {  Name = "SANTA LÚCIA",                           Acronym = "LC",           CountryCode= "+1",                  Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "SÃO CRISTÓVÃO E NEVIS",                 Acronym = "KN",           CountryCode= "+1",                  Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "SÃO MARINO",                            Acronym =  "SM",          CountryCode= "+378",                Continent = "EUROPA" },
            new Country ()  {  Name = "SÃO PEDRO E MIQUELÃO",                  Acronym =  "PM",          CountryCode= "+508",                Continent = "AMERICA DO NORTE" }, 
            new Country ()  {  Name = "SÃO TOMÉ E PRÍNCIPE",                   Acronym = "ST",           CountryCode= "+239",                Continent = "AFRICA" },
            new Country ()  {  Name = "SÃO VICENTE E GRANADINAS",              Acronym = "VC",           CountryCode= "+1",                  Continent = "AMERICA CENTRAL" },
            new Country ()  {  Name = "SENEGAL",                               Acronym = "SN",           CountryCode= "+221",                Continent = "AFRICA" },
            new Country ()  {  Name = "SERRA LEOA",                            Acronym = "SL",           CountryCode= "+232",                Continent = "AFRICA" },
            new Country ()  {  Name = "SÉRVIA",                                Acronym = "RS",           CountryCode= "+381",                Continent = "EUROPA" },
            new Country ()  {  Name = "SINGAPURA",                             Acronym = "SG",           CountryCode= "+65",                 Continent = "ASIA" },
            new Country ()  {  Name = "SÍRIA",                                 Acronym = "SY",           CountryCode= "+963",                Continent = "AFRICA" },
            new Country ()  {  Name = "SOMÁLIA",                               Acronym = "SO",           CountryCode= "+252",                Continent = "AFRICA" },
            new Country ()  {  Name = "SRI LANKA",                             Acronym = "LK",           CountryCode= "+94",                 Continent = "ASIA" },
            new Country ()  {  Name = "SUAZILÂNDIA",                           Acronym = "SZ",           CountryCode= "+268",                Continent = "AFRICA" },
            new Country ()  {  Name = "SUDÃO",                                 Acronym = "SD",           CountryCode= "+249",                Continent = "AFRICA" },
            new Country ()  {  Name = "SUDÃO DO SUL",                          Acronym = "SS",           CountryCode= "+211",                Continent = "AFRICA" }, 
            new Country ()  { Name =   "SUÉCIA",                               Acronym = "SE",           CountryCode= "+46",                 Continent = "EUROPA" },
            new Country ()  { Name =  "SUÍÇA",                                 Acronym = "CH",           CountryCode= "+41",                 Continent = "EUROPA" },
            new Country ()  { Name =  "SURINAME",                              Acronym = "SR",           CountryCode= "+597",                Continent = "AMERICA DO SUL" },
            new Country ()  { Name =  "SVALBARD E JAN MAYEN",                  Acronym = "SJ",           CountryCode= "+47",                 Continent = "EUROPA" },
            new Country ()  { Name =  "TADJIQUISTÃO",                          Acronym = "TJ",           CountryCode= "+992",                Continent = "ASIA" },
            new Country ()  { Name =  "TAILÂNDIA",                             Acronym = "TH",           CountryCode= "+66 ",                Continent = "ASIA" },
            new Country ()  { Name =  "TAIWAN",                                Acronym = "TW",           CountryCode= "+886",                Continent = "ASIA" },
            new Country ()  { Name =  "TANZÂNIA",                              Acronym = "TZ",           CountryCode= "+255",                Continent = "AFRICA" },
            new Country ()  { Name =  "TERRITÓRIO BRITÂNICO DO OCEANO ÍNDICO", Acronym = "IO",           CountryCode = "+246",               Continent = "AFRICA" },
            new Country ()  { Name =  "TIMOR LESTE",                           Acronym = "TP",           CountryCode= "+670 ",               Continent = "ASIA" },
            new Country ()  { Name =  "TOGO",                                  Acronym = "TG",           CountryCode= "+228",                Continent = "AFRICA" },
            new Country ()  { Name =  "TONGA",                                 Acronym = "TO",           CountryCode= "+676",                Continent = "OCEANIA" },
            new Country ()  { Name =  "TOQUELAU",                              Acronym = "TK",           CountryCode = "+690",               Continent = "OCEANIA" },
            new Country ()  { Name =  "TRINDAD E TOBAGO",                      Acronym = "TT",           CountryCode= "+1",                  Continent = "AMERICA CENTRAL" },
            new Country ()  { Name =  "TUNÍSIA",                               Acronym = "TN",           CountryCode= "+216",                Continent = "AFRICA" },
             new Country ()  { Name =  "TURCOMENISTÃO",                        Acronym = "TM",           CountryCode= "+993",                Continent = "ASIA" },
             new Country ()  { Name =  "TURQUIA",                              Acronym = "TR",           CountryCode= "+90",                 Continent = "ASIA/EUROPA" },
             new Country ()  { Name =  "TUVALU",                               Acronym = "TV",           CountryCode= "+688",                Continent = "OCEANIA" },
             new Country ()  { Name =  "UCRÂNIA",                              Acronym = "UA",           CountryCode= "+380",                Continent = "EUROPA" },
             new Country ()  { Name =  "UGANDA",                               Acronym = "UG",           CountryCode= "+256",                Continent = "AFRICA" },
             new Country ()  { Name =  "URUGUAI",                              Acronym = "UY",           CountryCode= "+598",                Continent = "AMERICA DO SUL" },
             new Country ()  { Name =  "UZBEQUISTÃO",                          Acronym = "UZ",           CountryCode= "+998",                Continent = "ASIA" },
             new Country ()  { Name =  "VANUATU",                              Acronym = "VU",           CountryCode= "+678",                Continent = "OCEANIA" },
             new Country ()  { Name =  "VATICANO",                             Acronym = "VA",           CountryCode= "+379",                Continent = "EUROPA" },
             new Country ()  { Name =  "VENEZUELA",                            Acronym = "VE",           CountryCode= "+58",                 Continent = "AMERICA DO SUL" },
             new Country ()  { Name =  "VIETNÃ",                               Acronym = "VN",           CountryCode= "+84",                 Continent = "ASIA" },
             new Country ()  { Name =  "WALLIS E FUTUNA",                      Acronym = "WF",           CountryCode = "+681",               Continent = "OCEANIA" },
             new Country ()  { Name =  "ZÂMBIA",                               Acronym = "ZM",           CountryCode= "+260",                Continent = "AFRICA" },
             new Country ()  { Name =  "ZIMBÁBWE",                             Acronym = "ZW",           CountryCode= "+263",                Continent = "AFRICA" },
    };
}
